"""
Script complet pour ajouter TOUTES les traductions manquantes dans TOUTES les langues
Langues supportées: FR, EN, ES (Espagnol), ZH (Chinois), JA (Japonais), IT (Italien), DE (Allemand), PT (Portugais), RU (Russe), AR (Arabe), KO (Coréen), NL (Néerlandais)
"""
import json
import re
from pathlib import Path
from typing import Dict, Set

# Configuration des langues
LANGUAGES = {
    'en': 'English',
    'fr': 'Français',
    'es': 'Español',
    'zh': '中文',
    'ja': '日本語',
    'it': 'Italiano',
    'de': 'Deutsch',
    'pt': 'Português',
    'ru': 'Русский',
    'ar': 'العربية',
    'ko': '한국어',
    'nl': 'Nederlands'
}

# Dictionnaire massif de traductions pour toutes les clés existantes et nouvelles
TRANSLATIONS = {
    # === NAVIGATION & UI PRINCIPAL ===
    "Home": {"en": "Home", "fr": "Accueil", "es": "Inicio", "zh": "首页", "ja": "ホーム", "it": "Home", "de": "Startseite", "pt": "Início", "ru": "Главная", "ar": "الرئيسية", "ko": "홈", "nl": "Home"},
    "Login": {"en": "Login", "fr": "Connexion", "es": "Iniciar sesión", "zh": "登录", "ja": "ログイン", "it": "Accedi", "de": "Anmelden", "pt": "Entrar", "ru": "Войти", "ar": "تسجيل الدخول", "ko": "로그인", "nl": "Inloggen"},
    "About": {"en": "About", "fr": "À propos", "es": "Acerca de", "zh": "关于", "ja": "について", "it": "Chi siamo", "de": "Über uns", "pt": "Sobre", "ru": "О нас", "ar": "حول", "ko": "정보", "nl": "Over"},
    "Calendar": {"en": "Calendar", "fr": "Calendrier", "es": "Calendario", "zh": "日历", "ja": "カレンダー", "it": "Calendario", "de": "Kalender", "pt": "Calendário", "ru": "Календарь", "ar": "التقويم", "ko": "달력", "nl": "Kalender"},
    "Mail": {"en": "Mail", "fr": "Mail", "es": "Correo", "zh": "邮件", "ja": "メール", "it": "Posta", "de": "Mail", "pt": "Email", "ru": "Почта", "ar": "البريد", "ko": "메일", "nl": "E-mail"},
    "Drive": {"en": "Drive", "fr": "Drive", "es": "Drive", "zh": "云盘", "ja": "ドライブ", "it": "Drive", "de": "Drive", "pt": "Drive", "ru": "Диск", "ar": "محرك الأقراص", "ko": "드라이브", "nl": "Drive"},
    "Chat": {"en": "Chat", "fr": "Chat", "es": "Chat", "zh": "聊天", "ja": "チャット", "it": "Chat", "de": "Chat", "pt": "Chat", "ru": "Чат", "ar": "الدردشة", "ko": "채팅", "nl": "Chat"},
    "Account": {"en": "Account", "fr": "Compte", "es": "Cuenta", "zh": "账户", "ja": "アカウント", "it": "Account", "de": "Konto", "pt": "Conta", "ru": "Аккаунт", "ar": "الحساب", "ko": "계정", "nl": "Account"},
    "Settings": {"en": "Settings", "fr": "Paramètres", "es": "Configuración", "zh": "设置", "ja": "設定", "it": "Impostazioni", "de": "Einstellungen", "pt": "Configurações", "ru": "Настройки", "ar": "الإعدادات", "ko": "설정", "nl": "Instellingen"},
    "Logout": {"en": "Logout", "fr": "Déconnexion", "es": "Cerrar sesión", "zh": "登出", "ja": "ログアウト", "it": "Esci", "de": "Abmelden", "pt": "Sair", "ru": "Выйти", "ar": "تسجيل الخروج", "ko": "로그아웃", "nl": "Uitloggen"},
    
    # === ACTIONS COMMUNES ===
    "cancel": {"en": "Cancel", "fr": "Annuler", "es": "Cancelar", "zh": "取消", "ja": "キャンセル", "it": "Annulla", "de": "Abbrechen", "pt": "Cancelar", "ru": "Отмена", "ar": "إلغاء", "ko": "취소", "nl": "Annuleren"},
    "confirm": {"en": "Confirm", "fr": "Confirmer", "es": "Confirmar", "zh": "确认", "ja": "確認", "it": "Conferma", "de": "Bestätigen", "pt": "Confirmar", "ru": "Подтвердить", "ar": "تأكيد", "ko": "확인", "nl": "Bevestigen"},
    "save": {"en": "Save", "fr": "Enregistrer", "es": "Guardar", "zh": "保存", "ja": "保存", "it": "Salva", "de": "Speichern", "pt": "Salvar", "ru": "Сохранить", "ar": "حفظ", "ko": "저장", "nl": "Opslaan"},
    "delete": {"en": "Delete", "fr": "Supprimer", "es": "Eliminar", "zh": "删除", "ja": "削除", "it": "Elimina", "de": "Löschen", "pt": "Excluir", "ru": "Удалить", "ar": "حذف", "ko": "삭제", "nl": "Verwijderen"},
    "edit": {"en": "Edit", "fr": "Modifier", "es": "Editar", "zh": "编辑", "ja": "編集", "it": "Modifica", "de": "Bearbeiten", "pt": "Editar", "ru": "Редактировать", "ar": "تعديل", "ko": "수정", "nl": "Bewerken"},
    "download": {"en": "Download", "fr": "Télécharger", "es": "Descargar", "zh": "下载", "ja": "ダウンロード", "it": "Scarica", "de": "Herunterladen", "pt": "Baixar", "ru": "Скачать", "ar": "تحميل", "ko": "다운로드", "nl": "Downloaden"},
    "upload": {"en": "Upload", "fr": "Téléverser", "es": "Subir", "zh": "上传", "ja": "アップロード", "it": "Carica", "de": "Hochladen", "pt": "Enviar", "ru": "Загрузить", "ar": "رفع", "ko": "업로드", "nl": "Uploaden"},
    "share": {"en": "Share", "fr": "Partager", "es": "Compartir", "zh": "分享", "ja": "共有", "it": "Condividi", "de": "Teilen", "pt": "Compartilhar", "ru": "Поделиться", "ar": "مشاركة", "ko": "공유", "nl": "Delen"},
    "search": {"en": "Search", "fr": "Rechercher", "es": "Buscar", "zh": "搜索", "ja": "検索", "it": "Cerca", "de": "Suchen", "pt": "Pesquisar", "ru": "Поиск", "ar": "بحث", "ko": "검색", "nl": "Zoeken"},
    "close": {"en": "Close", "fr": "Fermer", "es": "Cerrar", "zh": "关闭", "ja": "閉じる", "it": "Chiudi", "de": "Schließen", "pt": "Fechar", "ru": "Закрыть", "ar": "إغلاق", "ko": "닫기", "nl": "Sluiten"},
    "open": {"en": "Open", "fr": "Ouvrir", "es": "Abrir", "zh": "打开", "ja": "開く", "it": "Apri", "de": "Öffnen", "pt": "Abrir", "ru": "Открыть", "ar": "فتح", "ko": "열기", "nl": "Openen"},
    "refresh": {"en": "Refresh", "fr": "Actualiser", "es": "Actualizar", "zh": "刷新", "ja": "更新", "it": "Aggiorna", "de": "Aktualisieren", "pt": "Atualizar", "ru": "Обновить", "ar": "تحديث", "ko": "새로고침", "nl": "Vernieuwen"},
    "send": {"en": "Send", "fr": "Envoyer", "es": "Enviar", "zh": "发送", "ja": "送信", "it": "Invia", "de": "Senden", "pt": "Enviar", "ru": "Отправить", "ar": "إرسال", "ko": "보내기", "nl": "Verzenden"},
    "reply": {"en": "Reply", "fr": "Répondre", "es": "Responder", "zh": "回复", "ja": "返信", "it": "Rispondi", "de": "Antworten", "pt": "Responder", "ru": "Ответить", "ar": "رد", "ko": "답장", "nl": "Antwoorden"},
    "forward": {"en": "Forward", "fr": "Transférer", "es": "Reenviar", "zh": "转发", "ja": "転送", "it": "Inoltra", "de": "Weiterleiten", "pt": "Encaminhar", "ru": "Переслать", "ar": "إعادة توجيه", "ko": "전달", "nl": "Doorsturen"},
    
    # === ATTRIBUTS FICHIERS/EMAILS ===
    "name": {"en": "Name", "fr": "Nom", "es": "Nombre", "zh": "名称", "ja": "名前", "it": "Nome", "de": "Name", "pt": "Nome", "ru": "Имя", "ar": "الاسم", "ko": "이름", "nl": "Naam"},
    "size": {"en": "Size", "fr": "Taille", "es": "Tamaño", "zh": "大小", "ja": "サイズ", "it": "Dimensione", "de": "Größe", "pt": "Tamanho", "ru": "Размер", "ar": "الحجم", "ko": "크기", "nl": "Grootte"},
    "type": {"en": "Type", "fr": "Type", "es": "Tipo", "zh": "类型", "ja": "タイプ", "it": "Tipo", "de": "Typ", "pt": "Tipo", "ru": "Тип", "ar": "النوع", "ko": "유형", "nl": "Type"},
    "owner": {"en": "Owner", "fr": "Propriétaire", "es": "Propietario", "zh": "所有者", "ja": "所有者", "it": "Proprietario", "de": "Besitzer", "pt": "Proprietário", "ru": "Владелец", "ar": "المالك", "ko": "소유자", "nl": "Eigenaar"},
    "location": {"en": "Location", "fr": "Emplacement", "es": "Ubicación", "zh": "位置", "ja": "場所", "it": "Posizione", "de": "Standort", "pt": "Localização", "ru": "Местоположение", "ar": "الموقع", "ko": "위치", "nl": "Locatie"},
    "date": {"en": "Date", "fr": "Date", "es": "Fecha", "zh": "日期", "ja": "日付", "it": "Data", "de": "Datum", "pt": "Data", "ru": "Дата", "ar": "التاريخ", "ko": "날짜", "nl": "Datum"},
    "modified": {"en": "Modified", "fr": "Modifié", "es": "Modificado", "zh": "修改时间", "ja": "変更日時", "it": "Modificato", "de": "Geändert", "pt": "Modificado", "ru": "Изменено", "ar": "معدل", "ko": "수정됨", "nl": "Gewijzigd"},
    "created": {"en": "Created", "fr": "Créé", "es": "Creado", "zh": "创建时间", "ja": "作成日時", "it": "Creato", "de": "Erstellt", "pt": "Criado", "ru": "Создано", "ar": "تم الإنشاء", "ko": "생성됨", "nl": "Aangemaakt"},
    
    # === MESSAGES & NOTIFICATIONS ===
    "success": {"en": "Success", "fr": "Succès", "es": "Éxito", "zh": "成功", "ja": "成功", "it": "Successo", "de": "Erfolg", "pt": "Sucesso", "ru": "Успех", "ar": "نجاح", "ko": "성공", "nl": "Succes"},
    "error": {"en": "Error", "fr": "Erreur", "es": "Error", "zh": "错误", "ja": "エラー", "it": "Errore", "de": "Fehler", "pt": "Erro", "ru": "Ошибка", "ar": "خطأ", "ko": "오류", "nl": "Fout"},
    "warning": {"en": "Warning", "fr": "Avertissement", "es": "Advertencia", "zh": "警告", "ja": "警告", "it": "Avviso", "de": "Warnung", "pt": "Aviso", "ru": "Предупреждение", "ar": "تحذير", "ko": "경고", "nl": "Waarschuwing"},
    "loading": {"en": "Loading...", "fr": "Chargement...", "es": "Cargando...", "zh": "加载中...", "ja": "読み込み中...", "it": "Caricamento...", "de": "Laden...", "pt": "Carregando...", "ru": "Загрузка...", "ar": "جاري التحميل...", "ko": "로딩 중...", "nl": "Laden..."},
    
    # === DRIVE SPÉCIFIQUE ===
    "myFiles": {"en": "My Files", "fr": "Mes fichiers", "es": "Mis archivos", "zh": "我的文件", "ja": "マイファイル", "it": "I miei file", "de": "Meine Dateien", "pt": "Meus arquivos", "ru": "Мои файлы", "ar": "ملفاتي", "ko": "내 파일", "nl": "Mijn bestanden"},
    "shared": {"en": "Shared", "fr": "Partagés", "es": "Compartidos", "zh": "共享", "ja": "共有", "it": "Condivisi", "de": "Geteilt", "pt": "Compartilhados", "ru": "Общие", "ar": "مشتركة", "ko": "공유됨", "nl": "Gedeeld"},
    "trash": {"en": "Trash", "fr": "Corbeille", "es": "Papelera", "zh": "回收站", "ja": "ゴミ箱", "it": "Cestino", "de": "Papierkorb", "pt": "Lixeira", "ru": "Корзина", "ar": "سلة المهملات", "ko": "휴지통", "nl": "Prullenbak"},
    "newFolder": {"en": "New Folder", "fr": "Nouveau dossier", "es": "Nueva carpeta", "zh": "新建文件夹", "ja": "新しいフォルダ", "it": "Nuova cartella", "de": "Neuer Ordner", "pt": "Nova pasta", "ru": "Новая папка", "ar": "مجلد جديد", "ko": "새 폴더", "nl": "Nieuwe map"},
    "newFile": {"en": "New File", "fr": "Nouveau fichier", "es": "Nuevo archivo", "zh": "新建文件", "ja": "新しいファイル", "it": "Nuovo file", "de": "Neue Datei", "pt": "Novo arquivo", "ru": "Новый файл", "ar": "ملف جديد", "ko": "새 파일", "nl": "Nieuw bestand"},
    "storage": {"en": "Storage", "fr": "Stockage", "es": "Almacenamiento", "zh": "存储", "ja": "ストレージ", "it": "Archiviazione", "de": "Speicher", "pt": "Armazenamento", "ru": "Хранилище", "ar": "التخزين", "ko": "저장소", "nl": "Opslag"},
    "storageUsed": {"en": "Storage used", "fr": "Espace utilisé", "es": "Almacenamiento usado", "zh": "已用空间", "ja": "使用容量", "it": "Spazio utilizzato", "de": "Verwendeter Speicher", "pt": "Armazenamento usado", "ru": "Использовано", "ar": "المساحة المستخدمة", "ko": "사용된 저장소", "nl": "Gebruikt"},
    "unlimited": {"en": "Unlimited", "fr": "Illimité", "es": "Ilimitado", "zh": "无限", "ja": "無制限", "it": "Illimitato", "de": "Unbegrenzt", "pt": "Ilimitado", "ru": "Неограничено", "ar": "غير محدود", "ko": "무제한", "nl": "Onbeperkt"},
    
    # === MAIL SPÉCIFIQUE ===
    "inbox": {"en": "Inbox", "fr": "Boîte de réception", "es": "Bandeja de entrada", "zh": "收件箱", "ja": "受信トレイ", "it": "Posta in arrivo", "de": "Posteingang", "pt": "Caixa de entrada", "ru": "Входящие", "ar": "صندوق الوارد", "ko": "받은 편지함", "nl": "Postvak IN"},
    "draft": {"en": "Draft", "fr": "Brouillon", "es": "Borrador", "zh": "草稿", "ja": "下書き", "it": "Bozza", "de": "Entwurf", "pt": "Rascunho", "ru": "Черновик", "ar": "مسودة", "ko": "임시 보관함", "nl": "Concept"},
    "sent": {"en": "Sent", "fr": "Envoyés", "es": "Enviados", "zh": "已发送", "ja": "送信済み", "it": "Inviati", "de": "Gesendet", "pt": "Enviados", "ru": "Отправленные", "ar": "المرسلة", "ko": "보낸 편지함", "nl": "Verzonden"},
    "composeMail": {"en": "Compose Mail", "fr": "Écrire un mail", "es": "Redactar correo", "zh": "写邮件", "ja": "メール作成", "it": "Scrivi email", "de": "E-Mail verfassen", "pt": "Escrever email", "ru": "Написать письмо", "ar": "إنشاء بريد", "ko": "메일 작성", "nl": "E-mail opstellen"},
    "subject": {"en": "Subject", "fr": "Sujet", "es": "Asunto", "zh": "主题", "ja": "件名", "it": "Oggetto", "de": "Betreff", "pt": "Assunto", "ru": "Тема", "ar": "الموضوع", "ko": "제목", "nl": "Onderwerp"},
    "attachments": {"en": "Attachments", "fr": "Pièces jointes", "es": "Archivos adjuntos", "zh": "附件", "ja": "添付ファイル", "it": "Allegati", "de": "Anhänge", "pt": "Anexos", "ru": "Вложения", "ar": "المرفقات", "ko": "첨부 파일", "nl": "Bijlagen"},
    
    # === COMPTE & AUTH ===
    "username": {"en": "Username", "fr": "Nom d'utilisateur", "es": "Usuario", "zh": "用户名", "ja": "ユーザー名", "it": "Nome utente", "de": "Benutzername", "pt": "Nome de usuário", "ru": "Имя пользователя", "ar": "اسم المستخدم", "ko": "사용자 이름", "nl": "Gebruikersnaam"},
    "password": {"en": "Password", "fr": "Mot de passe", "es": "Contraseña", "zh": "密码", "ja": "パスワード", "it": "Password", "de": "Passwort", "pt": "Senha", "ru": "Пароль", "ar": "كلمة المرور", "ko": "비밀번호", "nl": "Wachtwoord"},
    "email": {"en": "Email", "fr": "Email", "es": "Correo electrónico", "zh": "电子邮件", "ja": "メールアドレス", "it": "Email", "de": "E-Mail", "pt": "E-mail", "ru": "Электронная почта", "ar": "البريد الإلكتروني", "ko": "이메일", "nl": "E-mail"},
    "phoneNumber": {"en": "Phone number", "fr": "Numéro de téléphone", "es": "Número de teléfono", "zh": "电话号码", "ja": "電話番号", "it": "Numero di telefono", "de": "Telefonnummer", "pt": "Número de telefone", "ru": "Номер телефона", "ar": "رقم الهاتف", "ko": "전화번호", "nl": "Telefoonnummer"},
    "forgotPassword": {"en": "Forgot password?", "fr": "Mot de passe oublié ?", "es": "¿Olvidó su contraseña?", "zh": "忘记密码？", "ja": "パスワードをお忘れですか？", "it": "Password dimenticata?", "de": "Passwort vergessen?", "pt": "Esqueceu a senha?", "ru": "Забыли пароль?", "ar": "نسيت كلمة المرور؟", "ko": "비밀번호를 잊으셨나요?", "nl": "Wachtwoord vergeten?"},
    "createAccount": {"en": "Create account", "fr": "Créer un compte", "es": "Crear cuenta", "zh": "创建账户", "ja": "アカウントを作成", "it": "Crea account", "de": "Konto erstellen", "pt": "Criar conta", "ru": "Создать аккаунт", "ar": "إنشاء حساب", "ko": "계정 만들기", "nl": "Account aanmaken"},
    "resetPassword": {"en": "Reset password", "fr": "Réinitialiser le mot de passe", "es": "Restablecer contraseña", "zh": "重置密码", "ja": "パスワードをリセット", "it": "Reimposta password", "de": "Passwort zurücksetzen", "pt": "Redefinir senha", "ru": "Сбросить пароль", "ar": "إعادة تعيين كلمة المرور", "ko": "비밀번호 재설정", "nl": "Wachtwoord resetten"},
    "enterNewPassword": {"en": "Enter your new password", "fr": "Entrez votre nouveau mot de passe", "es": "Ingrese su nueva contraseña", "zh": "输入新密码", "ja": "新しいパスワードを入力", "it": "Inserisci la tua nuova password", "de": "Geben Sie Ihr neues Passwort ein", "pt": "Digite sua nova senha", "ru": "Введите новый пароль", "ar": "أدخل كلمة المرور الجديدة", "ko": "새 비밀번호를 입력하세요", "nl": "Voer uw nieuwe wachtwoord in"},
    "confirmPassword": {"en": "Confirm your password", "fr": "Confirmez votre mot de passe", "es": "Confirme su contraseña", "zh": "确认密码", "ja": "パスワードを確認", "it": "Conferma la tua password", "de": "Bestätigen Sie Ihr Passwort", "pt": "Confirme sua senha", "ru": "Подтвердите пароль", "ar": "تأكيد كلمة المرور", "ko": "비밀번호 확인", "nl": "Bevestig uw wachtwoord"},
    "passwordMismatch": {"en": "Passwords do not match", "fr": "Les mots de passe ne correspondent pas", "es": "Las contraseñas no coinciden", "zh": "密码不匹配", "ja": "パスワードが一致しません", "it": "Le password non corrispondono", "de": "Passwörter stimmen nicht überein", "pt": "As senhas não coincidem", "ru": "Пароли не совпадают", "ar": "كلمات المرور غير متطابقة", "ko": "비밀번호가 일치하지 않습니다", "nl": "Wachtwoorden komen niet overeen"},
    
    # === ONLYOFFICE ===
    "openInOnlyOffice": {"en": "Open in OnlyOffice", "fr": "Ouvrir dans OnlyOffice", "es": "Abrir en OnlyOffice", "zh": "在OnlyOffice中打开", "ja": "OnlyOfficeで開く", "it": "Apri in OnlyOffice", "de": "In OnlyOffice öffnen", "pt": "Abrir no OnlyOffice", "ru": "Открыть в OnlyOffice", "ar": "فتح في OnlyOffice", "ko": "OnlyOffice에서 열기", "nl": "Openen in OnlyOffice"},
    "documentMustBeOpenedInOnlyOffice": {"en": "This document must be opened in the OnlyOffice editor.", "fr": "Ce document doit être ouvert dans l'éditeur OnlyOffice.", "es": "Este documento debe abrirse en el editor OnlyOffice.", "zh": "此文档必须在OnlyOffice编辑器中打开。", "ja": "このドキュメントはOnlyOfficeエディタで開く必要があります。", "it": "Questo documento deve essere aperto nell'editor OnlyOffice.", "de": "Dieses Dokument muss im OnlyOffice-Editor geöffnet werden.", "pt": "Este documento deve ser aberto no editor OnlyOffice.", "ru": "Этот документ должен быть открыт в редакторе OnlyOffice.", "ar": "يجب فتح هذا المستند في محرر OnlyOffice.", "ko": "이 문서는 OnlyOffice 편집기에서 열어야 합니다.", "nl": "Dit document moet worden geopend in de OnlyOffice-editor."},
    "noPreviewAvailable": {"en": "Preview not available for this file", "fr": "Aperçu non disponible pour ce fichier", "es": "Vista previa no disponible para este archivo", "zh": "此文件无法预览", "ja": "このファイルのプレビューは利用できません", "it": "Anteprima non disponibile per questo file", "de": "Vorschau für diese Datei nicht verfügbar", "pt": "Visualização não disponível para este arquivo", "ru": "Предпросмотр недоступен для этого файла", "ar": "المعاينة غير متوفرة لهذا الملف", "ko": "이 파일에 대한 미리보기를 사용할 수 없습니다", "nl": "Voorbeeld niet beschikbaar voor dit bestand"},
    
    # === DRIVE SPÉCIFIQUE (SUITE) ===
    "manageSecurely": {"en": "Manage your files securely", "fr": "Gérez vos fichiers en toute sécurité", "es": "Gestione sus archivos de forma segura", "zh": "安全管理您的文件", "ja": "ファイルを安全に管理", "it": "Gestisci i tuoi file in sicurezza", "de": "Verwalten Sie Ihre Dateien sicher", "pt": "Gerencie seus arquivos com segurança", "ru": "Управляйте файлами безопасно", "ar": "إدارة ملفاتك بشكل آمن", "ko": "파일을 안전하게 관리하세요", "nl": "Beheer uw bestanden veilig"},
    "folder": {"en": "Folder", "fr": "Dossier", "es": "Carpeta", "zh": "文件夹", "ja": "フォルダ", "it": "Cartella", "de": "Ordner", "pt": "Pasta", "ru": "Папка", "ar": "مجلد", "ko": "폴더", "nl": "Map"},
    "file": {"en": "File", "fr": "Fichier", "es": "Archivo", "zh": "文件", "ja": "ファイル", "it": "File", "de": "Datei", "pt": "Arquivo", "ru": "Файл", "ar": "ملف", "ko": "파일", "nl": "Bestand"},
    "items": {"en": "items", "fr": "éléments", "es": "elementos", "zh": "项", "ja": "項目", "it": "elementi", "de": "Elemente", "pt": "itens", "ru": "элементов", "ar": "عناصر", "ko": "항목", "nl": "items"},
    "almostFull": {"en": "Almost full!", "fr": "Espace presque plein !", "es": "¡Casi lleno!", "zh": "快满了！", "ja": "もうすぐいっぱい！", "it": "Quasi pieno!", "de": "Fast voll!", "pt": "Quase cheio!", "ru": "Почти заполнено!", "ar": "ممتلئ تقريباً!", "ko": "거의 가득 참!", "nl": "Bijna vol!"},
    "movingInProgress": {"en": "Moving in progress...", "fr": "Déplacement en cours…", "es": "Moviendo en progreso...", "zh": "移动中...", "ja": "移動中...", "it": "Spostamento in corso...", "de": "Verschieben läuft...", "pt": "Movendo em progresso...", "ru": "Перемещение...", "ar": "النقل جاري...", "ko": "이동 중...", "nl": "Verplaatsen bezig..."},
    "actions": {"en": "Actions", "fr": "Actions", "es": "Acciones", "zh": "操作", "ja": "アクション", "it": "Azioni", "de": "Aktionen", "pt": "Ações", "ru": "Действия", "ar": "الإجراءات", "ko": "작업", "nl": "Acties"},
    
    # === PASSWORD & SECURITY ===
    "resetPasswordTitle": {"en": "Reset Password", "fr": "Réinitialiser le mot de passe", "es": "Restablecer contraseña", "zh": "重置密码", "ja": "パスワードをリセット", "it": "Reimposta password", "de": "Passwort zurücksetzen", "pt": "Redefinir senha", "ru": "Сбросить пароль", "ar": "إعادة تعيين كلمة المرور", "ko": "비밀번호 재설정", "nl": "Wachtwoord resetten"},
    "createNewSecurePassword": {"en": "Create a new secure password", "fr": "Créez un nouveau mot de passe sécurisé", "es": "Cree una nueva contraseña segura", "zh": "创建新的安全密码", "ja": "新しい安全なパスワードを作成", "it": "Crea una nuova password sicura", "de": "Erstellen Sie ein neues sicheres Passwort", "pt": "Crie uma nova senha segura", "ru": "Создайте новый безопасный пароль", "ar": "إنشاء كلمة مرور آمنة جديدة", "ko": "새로운 보안 비밀번호 만들기", "nl": "Maak een nieuw beveiligd wachtwoord"},
    "newPassword": {"en": "New password", "fr": "Nouveau mot de passe", "es": "Nueva contraseña", "zh": "新密码", "ja": "新しいパスワード", "it": "Nuova password", "de": "Neues Passwort", "pt": "Nova senha", "ru": "Новый пароль", "ar": "كلمة مرور جديدة", "ko": "새 비밀번호", "nl": "Nieuw wachtwoord"},
    "confirmNewPassword": {"en": "Confirm your new password", "fr": "Confirmez votre nouveau mot de passe", "es": "Confirme su nueva contraseña", "zh": "确认您的新密码", "ja": "新しいパスワードを確認", "it": "Conferma la tua nuova password", "de": "Bestätigen Sie Ihr neues Passwort", "pt": "Confirme sua nova senha", "ru": "Подтвердите новый пароль", "ar": "تأكيد كلمة المرور الجديدة", "ko": "새 비밀번호 확인", "nl": "Bevestig uw nieuwe wachtwoord"},
    "passwordsDoNotMatch": {"en": "Passwords do not match", "fr": "Les mots de passe ne correspondent pas", "es": "Las contraseñas no coinciden", "zh": "密码不匹配", "ja": "パスワードが一致しません", "it": "Le password non corrispondono", "de": "Passwörter stimmen nicht überein", "pt": "As senhas não correspondem", "ru": "Пароли не совпадают", "ar": "كلمات المرور غير متطابقة", "ko": "비밀번호가 일치하지 않습니다", "nl": "Wachtwoorden komen niet overeen"},
    "passwordResetSuccess": {"en": "Password successfully reset!", "fr": "Mot de passe réinitialisé avec succès !", "es": "¡Contraseña restablecida con éxito!", "zh": "密码重置成功！", "ja": "パスワードが正常にリセットされました！", "it": "Password reimpostata con successo!", "de": "Passwort erfolgreich zurückgesetzt!", "pt": "Senha redefinida com sucesso!", "ru": "Пароль успешно сброшен!", "ar": "تم إعادة تعيين كلمة المرور بنجاح!", "ko": "비밀번호가 성공적으로 재설정되었습니다!", "nl": "Wachtwoord succesvol gereset!"},
    "passwordResetSuccessMessage": {"en": "Your password has been reset. You can now log in with your new password.", "fr": "Votre mot de passe a été réinitialisé. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.", "es": "Su contraseña ha sido restablecida. Ahora puede iniciar sesión con su nueva contraseña.", "zh": "您的密码已重置。您现在可以使用新密码登录。", "ja": "パスワードがリセットされました。新しいパスワードでログインできます。", "it": "La tua password è stata reimpostata. Ora puoi accedere con la tua nuova password.", "de": "Ihr Passwort wurde zurückgesetzt. Sie können sich jetzt mit Ihrem neuen Passwort anmelden.", "pt": "Sua senha foi redefinida. Agora você pode fazer login com sua nova senha.", "ru": "Ваш пароль был сброшен. Теперь вы можете войти с новым паролем.", "ar": "تم إعادة تعيين كلمة المرور الخاصة بك. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.", "ko": "비밀번호가 재설정되었습니다. 이제 새 비밀번호로 로그인할 수 있습니다.", "nl": "Uw wachtwoord is gereset. U kunt nu inloggen met uw nieuwe wachtwoord."},
    "backToLogin": {"en": "Back to login", "fr": "Retour à la connexion", "es": "Volver al inicio de sesión", "zh": "返回登录", "ja": "ログインに戻る", "it": "Torna al login", "de": "Zurück zur Anmeldung", "pt": "Voltar ao login", "ru": "Вернуться к входу", "ar": "العودة إلى تسجيل الدخول", "ko": "로그인으로 돌아가기", "nl": "Terug naar inloggen"},
    "requestNewLink": {"en": "Request a new link", "fr": "Demander un nouveau lien", "es": "Solicitar un nuevo enlace", "zh": "请求新链接", "ja": "新しいリンクをリクエスト", "it": "Richiedi un nuovo link", "de": "Neuen Link anfordern", "pt": "Solicitar um novo link", "ru": "Запросить новую ссылку", "ar": "طلب رابط جديد", "ko": "새 링크 요청", "nl": "Nieuwe link aanvragen"},
    
    # === CONTACT ===
    "contactUs": {"en": "Contact us", "fr": "Contactez-nous", "es": "Contáctenos", "zh": "联系我们", "ja": "お問い合わせ", "it": "Contattaci", "de": "Kontaktieren Sie uns", "pt": "Entre em contato", "ru": "Свяжитесь с нами", "ar": "اتصل بنا", "ko": "문의하기", "nl": "Neem contact op"},
    "hereToHelp": {"en": "We're here to help", "fr": "Nous sommes là pour vous aider", "es": "Estamos aquí para ayudar", "zh": "我们随时为您提供帮助", "ja": "お手伝いします", "it": "Siamo qui per aiutarti", "de": "Wir sind hier um zu helfen", "pt": "Estamos aqui para ajudar", "ru": "Мы здесь, чтобы помочь", "ar": "نحن هنا للمساعدة", "ko": "도와드리겠습니다", "nl": "We staan klaar om te helpen"},
    "fullName": {"en": "Full name", "fr": "Nom complet", "es": "Nombre completo", "zh": "全名", "ja": "フルネーム", "it": "Nome completo", "de": "Vollständiger Name", "pt": "Nome completo", "ru": "Полное имя", "ar": "الاسم الكامل", "ko": "전체 이름", "nl": "Volledige naam"},
    "yourName": {"en": "Your name", "fr": "Votre nom", "es": "Su nombre", "zh": "您的姓名", "ja": "お名前", "it": "Il tuo nome", "de": "Ihr Name", "pt": "Seu nome", "ru": "Ваше имя", "ar": "اسمك", "ko": "이름", "nl": "Uw naam"},
    "yourEmail": {"en": "your@email.com", "fr": "votre@email.com", "es": "su@email.com", "zh": "您的@邮箱.com", "ja": "あなた@メール.com", "it": "tuo@email.com", "de": "ihre@email.com", "pt": "seu@email.com", "ru": "ваш@email.com", "ar": "بريدك@الإلكتروني.com", "ko": "이메일@주소.com", "nl": "uw@email.com"},
    "phoneOptional": {"en": "Phone (optional)", "fr": "Téléphone (optionnel)", "es": "Teléfono (opcional)", "zh": "电话（可选）", "ja": "電話（任意）", "it": "Telefono (facoltativo)", "de": "Telefon (optional)", "pt": "Telefone (opcional)", "ru": "Телефон (необязательно)", "ar": "الهاتف (اختياري)", "ko": "전화 (선택사항)", "nl": "Telefoon (optioneel)"},
    "selectSubject": {"en": "Select a subject", "fr": "Sélectionnez un sujet", "es": "Seleccione un asunto", "zh": "选择主题", "ja": "件名を選択", "it": "Seleziona un oggetto", "de": "Wählen Sie ein Thema", "pt": "Selecione um assunto", "ru": "Выберите тему", "ar": "اختر موضوعاً", "ko": "주제 선택", "nl": "Selecteer een onderwerp"},
    "generalQuestion": {"en": "General question", "fr": "Question générale", "es": "Pregunta general", "zh": "一般问题", "ja": "一般的な質問", "it": "Domanda generale", "de": "Allgemeine Frage", "pt": "Pergunta geral", "ru": "Общий вопрос", "ar": "سؤال عام", "ko": "일반 질문", "nl": "Algemene vraag"},
    "technicalSupport": {"en": "Technical support", "fr": "Support technique", "es": "Soporte técnico", "zh": "技术支持", "ja": "技術サポート", "it": "Supporto tecnico", "de": "Technischer Support", "pt": "Suporte técnico", "ru": "Техническая поддержка", "ar": "الدعم الفني", "ko": "기술 지원", "nl": "Technische ondersteuning"},
    "sales": {"en": "Sales", "fr": "Ventes", "es": "Ventas", "zh": "销售", "ja": "営業", "it": "Vendite", "de": "Vertrieb", "pt": "Vendas", "ru": "Продажи", "ar": "المبيعات", "ko": "영업", "nl": "Verkoop"},
    "feedback": {"en": "Feedback", "fr": "Feedback", "es": "Comentarios", "zh": "反馈", "ja": "フィードバック", "it": "Feedback", "de": "Feedback", "pt": "Feedback", "ru": "Отзыв", "ar": "ملاحظات", "ko": "피드백", "nl": "Feedback"},
    "message": {"en": "Message", "fr": "Message", "es": "Mensaje", "zh": "消息", "ja": "メッセージ", "it": "Messaggio", "de": "Nachricht", "pt": "Mensagem", "ru": "Сообщение", "ar": "رسالة", "ko": "메시지", "nl": "Bericht"},
    "yourMessage": {"en": "Your message...", "fr": "Votre message...", "es": "Su mensaje...", "zh": "您的消息...", "ja": "メッセージ...", "it": "Il tuo messaggio...", "de": "Ihre Nachricht...", "pt": "Sua mensagem...", "ru": "Ваше сообщение...", "ar": "رسالتك...", "ko": "메시지...", "nl": "Uw bericht..."},
    "sendMessage": {"en": "Send message", "fr": "Envoyer le message", "es": "Enviar mensaje", "zh": "发送消息", "ja": "メッセージを送信", "it": "Invia messaggio", "de": "Nachricht senden", "pt": "Enviar mensagem", "ru": "Отправить сообщение", "ar": "إرسال رسالة", "ko": "메시지 보내기", "nl": "Bericht verzenden"},
    "messageSentSuccess": {"en": "Message sent successfully!", "fr": "Message envoyé avec succès !", "es": "¡Mensaje enviado con éxito!", "zh": "消息发送成功！", "ja": "メッセージが送信されました！", "it": "Messaggio inviato con successo!", "de": "Nachricht erfolgreich gesendet!", "pt": "Mensagem enviada com sucesso!", "ru": "Сообщение успешно отправлено!", "ar": "تم إرسال الرسالة بنجاح!", "ko": "메시지가 성공적으로 전송되었습니다!", "nl": "Bericht succesvol verzonden!"},
    "thankYouForContact": {"en": "Thank you for contacting us. We will get back to you soon.", "fr": "Merci de nous avoir contactés. Nous vous répondrons bientôt.", "es": "Gracias por contactarnos. Le responderemos pronto.", "zh": "感谢您联系我们。我们会尽快回复您。", "ja": "お問い合わせありがとうございます。すぐにご連絡いたします。", "it": "Grazie per averci contattato. Ti risponderemo presto.", "de": "Vielen Dank für Ihre Kontaktaufnahme. Wir werden uns bald bei Ihnen melden.", "pt": "Obrigado por entrar em contato. Retornaremos em breve.", "ru": "Спасибо за обращение. Мы скоро свяжемся с вами.", "ar": "شكراً لتواصلك معنا. سنرد عليك قريباً.", "ko": "문의해 주셔서 감사합니다. 곧 연락드리겠습니다.", "nl": "Bedankt voor uw contact. We nemen binnenkort contact op."},
    
    # === LOGOUT & CONFIRMATION ===
    "logout": {"en": "Logout", "fr": "Déconnexion", "es": "Cerrar sesión", "zh": "登出", "ja": "ログアウト", "it": "Esci", "de": "Abmelden", "pt": "Sair", "ru": "Выход", "ar": "تسجيل الخروج", "ko": "로그아웃", "nl": "Uitloggen"},
    "confirmLogout": {"en": "Are you sure you want to log out?", "fr": "Êtes-vous sûr de vouloir vous déconnecter ?", "es": "¿Está seguro de que desea cerrar sesión?", "zh": "您确定要登出吗？", "ja": "ログアウトしてもよろしいですか？", "it": "Sei sicuro di voler uscire?", "de": "Möchten Sie sich wirklich abmelden?", "pt": "Tem certeza de que deseja sair?", "ru": "Вы уверены, что хотите выйти?", "ar": "هل أنت متأكد من أنك تريد تسجيل الخروج؟", "ko": "로그아웃하시겠습니까?", "nl": "Weet u zeker dat u wilt uitloggen?"},
    "yes": {"en": "Yes", "fr": "Oui", "es": "Sí", "zh": "是", "ja": "はい", "it": "Sì", "de": "Ja", "pt": "Sim", "ru": "Да", "ar": "نعم", "ko": "예", "nl": "Ja"},
    "no": {"en": "No", "fr": "Non", "es": "No", "zh": "否", "ja": "いいえ", "it": "No", "de": "Nein", "pt": "Não", "ru": "Нет", "ar": "لا", "ko": "아니오", "nl": "Nee"},
    
    # === LOGIN & IDENTIFIANTS ===
    "connectionTitle": {"en": "Office1789 Connection", "fr": "Connexion Office1789", "es": "Conexión Office1789", "zh": "Office1789登录", "ja": "Office1789接続", "it": "Connessione Office1789", "de": "Office1789 Anmeldung", "pt": "Conexão Office1789", "ru": "Подключение Office1789", "ar": "اتصال Office1789", "ko": "Office1789 연결", "nl": "Office1789 Verbinding"},
    "accessCollaborativeSpace": {"en": "Access your collaborative space", "fr": "Accédez à votre espace collaboratif", "es": "Acceda a su espacio colaborativo", "zh": "访问您的协作空间", "ja": "コラボレーションスペースにアクセス", "it": "Accedi al tuo spazio collaborativo", "de": "Zugriff auf Ihren kollaborativen Raum", "pt": "Acesse seu espaço colaborativo", "ru": "Доступ к вашему совместному пространству", "ar": "الوصول إلى مساحتك التعاونية", "ko": "협업 공간 액세스", "nl": "Toegang tot uw samenwerkingsruimte"},
    "identifier": {"en": "Identifier", "fr": "Identifiant", "es": "Identificador", "zh": "标识符", "ja": "識別子", "it": "Identificatore", "de": "Kennung", "pt": "Identificador", "ru": "Идентификатор", "ar": "المعرف", "ko": "식별자", "nl": "Identificatie"},
    "yourIdentifier": {"en": "Your identifier", "fr": "Votre identifiant", "es": "Su identificador", "zh": "您的标识符", "ja": "あなたの識別子", "it": "Il tuo identificatore", "de": "Ihre Kennung", "pt": "Seu identificador", "ru": "Ваш идентификатор", "ar": "معرفك", "ko": "식별자", "nl": "Uw identificatie"},
    "yourPassword": {"en": "Your password", "fr": "Votre mot de passe", "es": "Su contraseña", "zh": "您的密码", "ja": "あなたのパスワード", "it": "La tua password", "de": "Ihr Passwort", "pt": "Sua senha", "ru": "Ваш пароль", "ar": "كلمة المرور الخاصة بك", "ko": "비밀번호", "nl": "Uw wachtwoord"},
    "showPassword": {"en": "Show password", "fr": "Afficher le mot de passe", "es": "Mostrar contraseña", "zh": "显示密码", "ja": "パスワードを表示", "it": "Mostra password", "de": "Passwort anzeigen", "pt": "Mostrar senha", "ru": "Показать пароль", "ar": "عرض كلمة المرور", "ko": "비밀번호 표시", "nl": "Wachtwoord tonen"},
    "twoFactorCode": {"en": "Two-factor authentication code", "fr": "Code d'authentification à 2 facteurs", "es": "Código de autenticación de dos factores", "zh": "双因素认证码", "ja": "2要素認証コード", "it": "Codice di autenticazione a due fattori", "de": "Zwei-Faktor-Authentifizierungscode", "pt": "Código de autenticação de dois fatores", "ru": "Код двухфакторной аутентификации", "ar": "رمز المصادقة الثنائية", "ko": "2단계 인증 코드", "nl": "Tweefactorauthenticatiecode"},
    "enterSixDigitCode": {"en": "Enter the 6-digit code from your authentication app", "fr": "Entrez le code à 6 chiffres de votre application d'authentification", "es": "Ingrese el código de 6 dígitos de su aplicación de autenticación", "zh": "输入您的身份验证应用程序中的6位数字代码", "ja": "認証アプリの6桁のコードを入力してください", "it": "Inserisci il codice a 6 cifre dalla tua app di autenticazione", "de": "Geben Sie den 6-stelligen Code aus Ihrer Authentifizierungs-App ein", "pt": "Digite o código de 6 dígitos do seu aplicativo de autenticação", "ru": "Введите 6-значный код из вашего приложения аутентификации", "ar": "أدخل الرمز المكون من 6 أرقام من تطبيق المصادقة الخاص بك", "ko": "인증 앱에서 6자리 코드를 입력하세요", "nl": "Voer de 6-cijferige code van uw authenticatie-app in"},
    "dontHaveAccount": {"en": "Don't have an account?", "fr": "Vous n'avez pas de compte ?", "es": "¿No tienes una cuenta?", "zh": "没有账户？", "ja": "アカウントをお持ちでない方", "it": "Non hai un account?", "de": "Sie haben kein Konto?", "pt": "Não tem uma conta?", "ru": "Нет аккаунта?", "ar": "لا تملك حساباً؟", "ko": "계정이 없으신가요?", "nl": "Heeft u geen account?"},
    "createAccountNow": {"en": "Create an account now", "fr": "Créer un compte maintenant", "es": "Crear una cuenta ahora", "zh": "立即创建账户", "ja": "今すぐアカウントを作成", "it": "Crea un account ora", "de": "Jetzt Konto erstellen", "pt": "Criar uma conta agora", "ru": "Создать аккаунт сейчас", "ar": "إنشاء حساب الآن", "ko": "지금 계정 만들기", "nl": "Maak nu een account aan"},
    "incorrectCredentials": {"en": "Incorrect username or password", "fr": "Identifiant ou mot de passe incorrect", "es": "Usuario o contraseña incorrectos", "zh": "用户名或密码不正确", "ja": "ユーザー名またはパスワードが正しくありません", "it": "Nome utente o password errati", "de": "Falscher Benutzername oder Passwort", "pt": "Nome de usuário ou senha incorretos", "ru": "Неверное имя пользователя или пароль", "ar": "اسم المستخدم أو كلمة المرور غير صحيحة", "ko": "사용자 이름 또는 비밀번호가 잘못되었습니다", "nl": "Onjuiste gebruikersnaam of wachtwoord"},
    "invalidTwoFactorCode": {"en": "Invalid two-factor authentication code", "fr": "Code d'authentification à 2 facteurs invalide", "es": "Código de autenticación de dos factores inválido", "zh": "双因素认证码无效", "ja": "2要素認証コードが無効です", "it": "Codice di autenticazione a due fattori non valido", "de": "Ungültiger Zwei-Faktor-Authentifizierungscode", "pt": "Código de autenticação de dois fatores inválido", "ru": "Неверный код двухфакторной аутентификации", "ar": "رمز المصادقة الثنائية غير صالح", "ko": "2단계 인증 코드가 잘못되었습니다", "nl": "Ongeldige tweefactorauthenticatiecode"},
    "firstConnection": {"en": "First time connecting?", "fr": "Première connexion ?", "es": "¿Primera conexión?", "zh": "首次连接？", "ja": "初めて接続しますか？", "it": "Prima connessione?", "de": "Erste Verbindung?", "pt": "Primeira conexão?", "ru": "Первый раз подключаетесь?", "ar": "الاتصال لأول مرة؟", "ko": "처음 연결하시나요?", "nl": "Eerste keer verbinden?"},
    "createAccountAndGet50GB": {"en": "Create your account for free and enjoy 50 GB of storage!", "fr": "Créez votre compte gratuitement et profitez de 50 Go de stockage !", "es": "¡Cree su cuenta gratis y disfrute de 50 GB de almacenamiento!", "zh": "免费创建您的帐户并享受50 GB存储空间！", "ja": "無料でアカウントを作成し、50GBのストレージをお楽しみください！", "it": "Crea il tuo account gratuitamente e goditi 50 GB di spazio di archiviazione!", "de": "Erstellen Sie kostenlos Ihr Konto und genießen Sie 50 GB Speicherplatz!", "pt": "Crie sua conta gratuitamente e aproveite 50 GB de armazenamento!", "ru": "Создайте свою учетную запись бесплатно и наслаждайтесь 50 ГБ хранилища!", "ar": "أنشئ حسابك مجانًا واستمتع بمساحة تخزين 50 جيجابايت!", "ko": "무료로 계정을 만들고 50GB 스토리지를 즐기세요!", "nl": "Maak gratis uw account aan en geniet van 50 GB opslagruimte!"},
    
    # === CREATE ACCOUNT ===
    "joinDigitalRevolution": {"en": "Join the French digital revolution", "fr": "Rejoignez la révolution numérique française", "es": "Únase a la revolución digital francesa", "zh": "加入法国数字革命", "ja": "フランスのデジタル革命に参加", "it": "Unisciti alla rivoluzione digitale francese", "de": "Treten Sie der französischen digitalen Revolution bei", "pt": "Junte-se à revolução digital francesa", "ru": "Присоединяйтесь к французской цифровой революции", "ar": "انضم إلى الثورة الرقمية الفرنسية", "ko": "프랑스 디지털 혁명에 참여하세요", "nl": "Sluit je aan bij de Franse digitale revolutie"},
    "accountInformation": {"en": "Account Information", "fr": "Informations du compte", "es": "Información de la cuenta", "zh": "账户信息", "ja": "アカウント情報", "it": "Informazioni sull'account", "de": "Kontoinformationen", "pt": "Informações da conta", "ru": "Информация об аккаунте", "ar": "معلومات الحساب", "ko": "계정 정보", "nl": "Accountinformatie"},
    "usernameField": {"en": "Username *", "fr": "Nom d'utilisateur *", "es": "Nombre de usuario *", "zh": "用户名 *", "ja": "ユーザー名 *", "it": "Nome utente *", "de": "Benutzername *", "pt": "Nome de usuário *", "ru": "Имя пользователя *", "ar": "اسم المستخدم *", "ko": "사용자 이름 *", "nl": "Gebruikersnaam *"},
    "passwordField": {"en": "Password *", "fr": "Mot de passe *", "es": "Contraseña *", "zh": "密码 *", "ja": "パスワード *", "it": "Password *", "de": "Passwort *", "pt": "Senha *", "ru": "Пароль *", "ar": "كلمة المرور *", "ko": "비밀번호 *", "nl": "Wachtwoord *"},
    "confirmPasswordField": {"en": "Confirm Password *", "fr": "Confirmer le mot de passe *", "es": "Confirmar contraseña *", "zh": "确认密码 *", "ja": "パスワードを確認 *", "it": "Conferma password *", "de": "Passwort bestätigen *", "pt": "Confirmar senha *", "ru": "Подтвердите пароль *", "ar": "تأكيد كلمة المرور *", "ko": "비밀번호 확인 *", "nl": "Bevestig wachtwoord *"},
    "personalInformation": {"en": "Personal Information", "fr": "Informations personnelles", "es": "Información personal", "zh": "个人信息", "ja": "個人情報", "it": "Informazioni personali", "de": "Persönliche Informationen", "pt": "Informações pessoais", "ru": "Личная информация", "ar": "معلومات شخصية", "ko": "개인 정보", "nl": "Persoonlijke informatie"},
    "emailField": {"en": "Email", "fr": "Email", "es": "Correo electrónico", "zh": "电子邮件", "ja": "メール", "it": "Email", "de": "E-Mail", "pt": "E-mail", "ru": "Электронная почта", "ar": "البريد الإلكتروني", "ko": "이메일", "nl": "E-mail"},
    "phoneNumberField": {"en": "Phone Number", "fr": "Numéro de téléphone", "es": "Número de teléfono", "zh": "电话号码", "ja": "電話番号", "it": "Numero di telefono", "de": "Telefonnummer", "pt": "Número de telefone", "ru": "Номер телефона", "ar": "رقم الهاتف", "ko": "전화번호", "nl": "Telefoonnummer"},
    "phonePlaceholder": {"en": "+33612345678 or 0612345678", "fr": "+33612345678 ou 0612345678", "es": "+33612345678 o 0612345678", "zh": "+33612345678 或 0612345678", "ja": "+33612345678 または 0612345678", "it": "+33612345678 o 0612345678", "de": "+33612345678 oder 0612345678", "pt": "+33612345678 ou 0612345678", "ru": "+33612345678 или 0612345678", "ar": "+33612345678 أو 0612345678", "ko": "+33612345678 또는 0612345678", "nl": "+33612345678 of 0612345678"},
    "invalidEmailFormat": {"en": "Invalid email format", "fr": "Format d'email invalide", "es": "Formato de correo electrónico inválido", "zh": "电子邮件格式无效", "ja": "メール形式が無効です", "it": "Formato email non valido", "de": "Ungültiges E-Mail-Format", "pt": "Formato de e-mail inválido", "ru": "Неверный формат электронной почты", "ar": "تنسيق البريد الإلكتروني غير صالح", "ko": "잘못된 이메일 형식", "nl": "Ongeldig e-mailformaat"},
    "invalidPhoneFormat": {"en": "Invalid phone format", "fr": "Format de téléphone invalide", "es": "Formato de teléfono inválido", "zh": "电话格式无效", "ja": "電話形式が無効です", "it": "Formato telefono non valido", "de": "Ungültiges Telefon-Format", "pt": "Formato de telefone inválido", "ru": "Неверный формат телефона", "ar": "تنسيق الهاتف غير صالح", "ko": "잘못된 전화번호 형식", "nl": "Ongeldig telefoonformaat"},
    "createMyAccount": {"en": "Create my account", "fr": "Créer mon compte", "es": "Crear mi cuenta", "zh": "创建我的账户", "ja": "アカウントを作成", "it": "Crea il mio account", "de": "Mein Konto erstellen", "pt": "Criar minha conta", "ru": "Создать мой аккаунт", "ar": "إنشاء حسابي", "ko": "내 계정 만들기", "nl": "Mijn account aanmaken"},
    "alreadyHaveAccount": {"en": "Already have an account? Log in", "fr": "Déjà un compte ? Se connecter", "es": "¿Ya tienes una cuenta? Iniciar sesión", "zh": "已经有账户？登录", "ja": "すでにアカウントをお持ちですか？ログイン", "it": "Hai già un account? Accedi", "de": "Bereits ein Konto? Anmelden", "pt": "Já tem uma conta? Entrar", "ru": "Уже есть аккаунт? Войти", "ar": "هل لديك حساب بالفعل؟ تسجيل الدخول", "ko": "이미 계정이 있으신가요? 로그인", "nl": "Al een account? Inloggen"},
    
    # === FORGOT PASSWORD ===
    "recoverAccountAccess": {"en": "Recover access to your account", "fr": "Récupérez l'accès à votre compte", "es": "Recupera el acceso a tu cuenta", "zh": "恢复对您帐户的访问", "ja": "アカウントへのアクセスを回復", "it": "Recupera l'accesso al tuo account", "de": "Wiederherstellung des Zugriffs auf Ihr Konto", "pt": "Recupere o acesso à sua conta", "ru": "Восстановите доступ к вашему аккаунту", "ar": "استعادة الوصول إلى حسابك", "ko": "계정 액세스 복구", "nl": "Herstel toegang tot uw account"},
    "identifierOrEmail": {"en": "Identifier or email", "fr": "Identifiant ou email", "es": "Identificador o correo electrónico", "zh": "标识符或电子邮件", "ja": "識別子またはメール", "it": "Identificatore o email", "de": "Kennung oder E-Mail", "pt": "Identificador ou e-mail", "ru": "Идентификатор или электронная почта", "ar": "المعرف أو البريد الإلكتروني", "ko": "식별자 또는 이메일", "nl": "Identificatie of e-mail"},
    "sendEmail": {"en": "Send email", "fr": "Envoyer l'email", "es": "Enviar correo electrónico", "zh": "发送电子邮件", "ja": "メールを送信", "it": "Invia email", "de": "E-Mail senden", "pt": "Enviar e-mail", "ru": "Отправить электронное письмо", "ar": "إرسال البريد الإلكتروني", "ko": "이메일 보내기", "nl": "E-mail versturen"},
    "sendingInProgress": {"en": "Sending in progress...", "fr": "Envoi en cours...", "es": "Envío en curso...", "zh": "正在发送...", "ja": "送信中...", "it": "Invio in corso...", "de": "Wird gesendet...", "pt": "Enviando...", "ru": "Отправка...", "ar": "جاري الإرسال...", "ko": "전송 중...", "nl": "Verzenden..."},
    "pleaseEnterIdentifier": {"en": "Please enter your identifier", "fr": "Veuillez entrer votre identifiant", "es": "Por favor, ingrese su identificador", "zh": "请输入您的标识符", "ja": "識別子を入力してください", "it": "Inserisci il tuo identificatore", "de": "Bitte geben Sie Ihre Kennung ein", "pt": "Por favor, insira seu identificador", "ru": "Пожалуйста, введите ваш идентификатор", "ar": "الرجاء إدخال معرفك", "ko": "식별자를 입력하세요", "nl": "Voer uw identificatie in"},
    "emailHasBeenSent": {"en": "An email has been sent to you", "fr": "Un email vient de vous être envoyé", "es": "Se le ha enviado un correo electrónico", "zh": "已向您发送电子邮件", "ja": "メールが送信されました", "it": "Ti è stata inviata un'email", "de": "Eine E-Mail wurde an Sie gesendet", "pt": "Um e-mail foi enviado para você", "ru": "Вам было отправлено электронное письмо", "ar": "تم إرسال بريد إلكتروني إليك", "ko": "이메일이 발송되었습니다", "nl": "Er is een e-mail naar u verzonden"},
    "backToLogin": {"en": "Back to login", "fr": "Retour à la connexion", "es": "Volver al inicio de sesión", "zh": "返回登录", "ja": "ログインに戻る", "it": "Torna al login", "de": "Zurück zur Anmeldung", "pt": "Voltar ao login", "ru": "Вернуться к входу", "ar": "العودة إلى تسجيل الدخول", "ko": "로그인으로 돌아가기", "nl": "Terug naar inloggen"},
    "forgotPasswordInfo": {"en": "Enter your identifier or email and we will send you a link to reset your password", "fr": "Entrez votre identifiant ou email et nous vous enverrons un lien pour réinitialiser votre mot de passe", "es": "Ingrese su identificador o correo electrónico y le enviaremos un enlace para restablecer su contraseña", "zh": "输入您的标识符或电子邮件，我们将向您发送重置密码的链接", "ja": "識別子またはメールを入力すると、パスワードをリセットするためのリンクをお送りします", "it": "Inserisci il tuo identificatore o email e ti invieremo un link per reimpostare la password", "de": "Geben Sie Ihre Kennung oder E-Mail ein und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts", "pt": "Digite seu identificador ou e-mail e enviaremos um link para redefinir sua senha", "ru": "Введите свой идентификатор или электронную почту, и мы отправим вам ссылку для сброса пароля", "ar": "أدخل معرفك أو بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور الخاصة بك", "ko": "식별자 또는 이메일을 입력하면 비밀번호를 재설정할 수 있는 링크를 보내드립니다", "nl": "Voer uw identificatie of e-mail in en we sturen u een link om uw wachtwoord opnieuw in te stellen"},
    
    # === HOME VIEW ===
    "theirPrivilegesOurRevolution": {"en": "Their privileges, our Revolution", "fr": "Leurs privilèges, notre Révolution", "es": "Sus privilegios, nuestra Revolución", "zh": "他们的特权，我们的革命", "ja": "彼らの特権、私たちの革命", "it": "I loro privilegi, la nostra Rivoluzione", "de": "Ihre Privilegien, unsere Revolution", "pt": "Seus privilégios, nossa Revolução", "ru": "Их привилегии, наша Революция", "ar": "امتيازاتهم، ثورتنا", "ko": "그들의 특권, 우리의 혁명", "nl": "Hun privileges, onze Revolutie"},
    "ourServices": {"en": "Our Services", "fr": "Nos Services", "es": "Nuestros Servicios", "zh": "我们的服务", "ja": "私たちのサービス", "it": "I nostri Servizi", "de": "Unsere Dienstleistungen", "pt": "Nossos Serviços", "ru": "Наши услуги", "ar": "خدماتنا", "ko": "우리의 서비스", "nl": "Onze Diensten"},
    "completeProductivityTools": {"en": "A complete suite of tools for your productivity", "fr": "Une suite complète d'outils pour votre productivité", "es": "Una suite completa de herramientas para su productividad", "zh": "完整的生产力工具套件", "ja": "生産性のための完全なツールスイート", "it": "Una suite completa di strumenti per la tua produttività", "de": "Eine vollständige Suite von Tools für Ihre Produktivität", "pt": "Um conjunto completo de ferramentas para sua produtividade", "ru": "Полный набор инструментов для вашей продуктивности", "ar": "مجموعة كاملة من الأدوات لإنتاجيتك", "ko": "생산성을 위한 완전한 도구 모음", "nl": "Een complete reeks tools voor uw productiviteit"},
    "messaging": {"en": "Messaging", "fr": "Messagerie", "es": "Mensajería", "zh": "消息传递", "ja": "メッセージング", "it": "Messaggistica", "de": "Messaging", "pt": "Mensagens", "ru": "Обмен сообщениями", "ar": "المراسلة", "ko": "메시징", "nl": "Berichten"},
    "professionalEmailWith10GB": {"en": "Professional email with 10 GB of storage, integrated calendar and centralized contacts", "fr": "Email professionnel avec 10 Go de stockage, calendrier intégré et contacts centralisés", "es": "Correo electrónico profesional con 10 GB de almacenamiento, calendario integrado y contactos centralizados", "zh": "专业电子邮件，10 GB存储空间，集成日历和集中联系人", "ja": "10GBのストレージ、統合カレンダー、集中連絡先を備えたプロフェッショナルメール", "it": "Email professionale con 10 GB di spazio di archiviazione, calendario integrato e contatti centralizzati", "de": "Professionelle E-Mail mit 10 GB Speicher, integriertem Kalender und zentralisierten Kontakten", "pt": "E-mail profissional com 10 GB de armazenamento, calendário integrado e contatos centralizados", "ru": "Профессиональная электронная почта с 10 ГБ хранилища, интегрированным календарем и централизованными контактами", "ar": "بريد إلكتروني احترافي مع 10 جيجابايت من التخزين، تقويم متكامل وجهات اتصال مركزية", "ko": "10GB 스토리지, 통합 캘린더 및 중앙 집중식 연락처가 있는 전문 이메일", "nl": "Professionele e-mail met 10 GB opslag, geïntegreerde agenda en gecentraliseerde contacten"},
    "chat": {"en": "Chat", "fr": "Chat", "es": "Chat", "zh": "聊天", "ja": "チャット", "it": "Chat", "de": "Chat", "pt": "Chat", "ru": "Чат", "ar": "الدردشة", "ko": "채팅", "nl": "Chat"},
    "instantCommunicationWithColleagues": {"en": "Instant communication with your colleagues, discussion groups and integrated calls", "fr": "Communication instantanée avec vos collaborateurs, groupes de discussion et appels intégrés", "es": "Comunicación instantánea con sus colegas, grupos de discusión y llamadas integradas", "zh": "与您的同事即时通信，讨论组和集成通话", "ja": "同僚とのインスタントコミュニケーション、ディスカッショングループ、統合通話", "it": "Comunicazione istantanea con i tuoi colleghi, gruppi di discussione e chiamate integrate", "de": "Sofortige Kommunikation mit Ihren Kollegen, Diskussionsgruppen und integrierten Anrufen", "pt": "Comunicação instantânea com seus colegas, grupos de discussão e chamadas integradas", "ru": "Мгновенная коммуникация с вашими коллегами, группы обсуждения и интегрированные звонки", "ar": "الاتصال الفوري مع زملائك، مجموعات المناقشة والمكالمات المتكاملة", "ko": "동료와의 즉각적인 커뮤니케이션, 토론 그룹 및 통합 통화", "nl": "Directe communicatie met uw collega's, discussiegroepen en geïntegreerde oproepen"},
    "cloudStorage": {"en": "Cloud Storage", "fr": "Stockage Cloud", "es": "Almacenamiento en la nube", "zh": "云存储", "ja": "クラウドストレージ", "it": "Archiviazione Cloud", "de": "Cloud-Speicher", "pt": "Armazenamento em Nuvem", "ru": "Облачное хранилище", "ar": "التخزين السحابي", "ko": "클라우드 스토리지", "nl": "Cloud Opslag"},
    "secureStorage50GB": {"en": "50 GB of secure storage for all your documents with easy sharing", "fr": "50 Go de stockage sécurisé pour tous vos documents avec partage facile", "es": "50 GB de almacenamiento seguro para todos sus documentos con uso compartido fácil", "zh": "50 GB安全存储空间，可轻松共享所有文档", "ja": "すべてのドキュメント用の50GBの安全なストレージと簡単な共有", "it": "50 GB di spazio di archiviazione sicuro per tutti i tuoi documenti con condivisione facile", "de": "50 GB sicherer Speicher für alle Ihre Dokumente mit einfacher Freigabe", "pt": "50 GB de armazenamento seguro para todos os seus documentos com compartilhamento fácil", "ru": "50 ГБ безопасного хранилища для всех ваших документов с легким общим доступом", "ar": "50 جيجابايت من التخزين الآمن لجميع مستنداتك مع مشاركة سهلة", "ko": "쉬운 공유로 모든 문서를 위한 50GB의 안전한 스토리지", "nl": "50 GB veilige opslag voor al uw documenten met eenvoudig delen"},
    "officeSuite": {"en": "Office Suite", "fr": "Suite Bureautique", "es": "Suite de Oficina", "zh": "办公套件", "ja": "オフィススイート", "it": "Suite per Ufficio", "de": "Office-Suite", "pt": "Suíte de Escritório", "ru": "Офисный пакет", "ar": "مجموعة المكتب", "ko": "오피스 제품군", "nl": "Kantoor Suite"},
    "textEditorSpreadsheetPresentation": {"en": "Text editor, spreadsheet and presentations with integrated OnlyOffice", "fr": "Éditeur de texte, tableur et présentations avec OnlyOffice intégré", "es": "Editor de texto, hoja de cálculo y presentaciones con OnlyOffice integrado", "zh": "文本编辑器、电子表格和演示文稿，集成OnlyOffice", "ja": "統合OnlyOfficeを備えたテキストエディター、スプレッドシート、プレゼンテーション", "it": "Editor di testo, foglio di calcolo e presentazioni con OnlyOffice integrato", "de": "Texteditor, Tabellenkalkulation und Präsentationen mit integriertem OnlyOffice", "pt": "Editor de texto, planilha e apresentações com OnlyOffice integrado", "ru": "Текстовый редактор, электронные таблицы и презентации с интегрированным OnlyOffice", "ar": "محرر النصوص، جدول البيانات والعروض التقديمية مع OnlyOffice المتكامل", "ko": "통합 OnlyOffice가 있는 텍스트 편집기, 스프레드시트 및 프레젠테이션", "nl": "Teksteditor, spreadsheet en presentaties met geïntegreerd OnlyOffice"},
    "calendarService": {"en": "Calendar", "fr": "Calendrier", "es": "Calendario", "zh": "日历", "ja": "カレンダー", "it": "Calendario", "de": "Kalender", "pt": "Calendário", "ru": "Календарь", "ar": "التقويم", "ko": "캘린더", "nl": "Kalender"},
    "organizeAppointmentsEvents": {"en": "Organize your appointments and events with a complete calendar", "fr": "Organisez vos rendez-vous et événements avec un calendrier complet", "es": "Organice sus citas y eventos con un calendario completo", "zh": "使用完整的日历组织您的约会和活动", "ja": "完全なカレンダーで予定とイベントを整理", "it": "Organizza i tuoi appuntamenti ed eventi con un calendario completo", "de": "Organisieren Sie Ihre Termine und Veranstaltungen mit einem vollständigen Kalender", "pt": "Organize seus compromissos e eventos com um calendário completo", "ru": "Организуйте свои встречи и события с помощью полного календаря", "ar": "نظم مواعيدك وأحداثك مع تقويم كامل", "ko": "완전한 캘린더로 약속과 이벤트를 정리하세요", "nl": "Organiseer uw afspraken en evenementen met een complete agenda"},
    
    # === ABOUT VIEW ===
    "aboutOffice1789": {"en": "About Office1789", "fr": "À propos d'Office1789", "es": "Acerca de Office1789", "zh": "关于Office1789", "ja": "Office1789について", "it": "Informazioni su Office1789", "de": "Über Office1789", "pt": "Sobre Office1789", "ru": "О Office1789", "ar": "حول Office1789", "ko": "Office1789 소개", "nl": "Over Office1789"},
    "discoverCollaborativeSuite": {"en": "Discover our sovereign collaborative suite", "fr": "Découvrez notre suite collaborative souveraine", "es": "Descubra nuestra suite colaborativa soberana", "zh": "发现我们的主权协作套件", "ja": "私たちの主権的コラボレーションスイートを発見", "it": "Scopri la nostra suite collaborativa sovrana", "de": "Entdecken Sie unsere souveräne kollaborative Suite", "pt": "Descubra nosso conjunto colaborativo soberano", "ru": "Откройте для себя наш суверенный совместный набор", "ar": "اكتشف مجموعتنا التعاونية السيادية", "ko": "우리의 주권적 협업 제품군을 발견하세요", "nl": "Ontdek ons soevereine samenwerkingspakket"},
    "ourMission": {"en": "Our Mission", "fr": "Notre Mission", "es": "Nuestra Misión", "zh": "我们的使命", "ja": "私たちの使命", "it": "La nostra Missione", "de": "Unsere Mission", "pt": "Nossa Missão", "ru": "Наша миссия", "ar": "مهمتنا", "ko": "우리의 사명", "nl": "Onze Missie"},
    "innovation": {"en": "Innovation", "fr": "Innovation", "es": "Innovación", "zh": "创新", "ja": "イノベーション", "it": "Innovazione", "de": "Innovation", "pt": "Inovação", "ru": "Инновации", "ar": "الابتكار", "ko": "혁신", "nl": "Innovatie"},
    "developModernTools": {"en": "Develop modern and efficient collaborative tools that compete with American giants", "fr": "Développer des outils collaboratifs modernes et performants qui rivalisent avec les géants américains", "es": "Desarrollar herramientas colaborativas modernas y eficientes que compitan con los gigantes estadounidenses", "zh": "开发现代高效的协作工具，与美国巨头竞争", "ja": "アメリカの巨人と競争する現代的で効率的なコラボレーションツールを開発", "it": "Sviluppare strumenti collaborativi moderni ed efficienti che competono con i giganti americani", "de": "Moderne und effiziente kollaborative Tools entwickeln, die mit amerikanischen Giganten konkurrieren", "pt": "Desenvolver ferramentas colaborativas modernas e eficientes que competem com os gigantes americanos", "ru": "Разрабатывать современные и эффективные совместные инструменты, конкурирующие с американскими гигантами", "ar": "تطوير أدوات تعاونية حديثة وفعالة تنافس العمالقة الأمريكيين", "ko": "미국 거대 기업과 경쟁하는 현대적이고 효율적인 협업 도구 개발", "nl": "Moderne en efficiënte samenwerkingstools ontwikkelen die concurreren met Amerikaanse giganten"},
    "sovereignty": {"en": "Sovereignty", "fr": "Souveraineté", "es": "Soberanía", "zh": "主权", "ja": "主権", "it": "Sovranità", "de": "Souveränität", "pt": "Soberania", "ru": "Суверенитет", "ar": "السيادة", "ko": "주권", "nl": "Soevereiniteit"},
    "guaranteeDataHosting": {"en": "Guarantee data hosting in France and Europe for total control", "fr": "Garantir l'hébergement de vos données en France et en Europe pour une totale maîtrise", "es": "Garantizar el alojamiento de datos en Francia y Europa para un control total", "zh": "保证在法国和欧洲托管数据以实现完全控制", "ja": "完全な制御のためにフランスとヨーロッパでのデータホスティングを保証", "it": "Garantire l'hosting dei dati in Francia e in Europa per un controllo totale", "de": "Garantieren Sie das Datenhosting in Frankreich und Europa für vollständige Kontrolle", "pt": "Garantir a hospedagem de dados na França e na Europa para controle total", "ru": "Гарантировать хостинг данных во Франции и Европе для полного контроля", "ar": "ضمان استضافة البيانات في فرنسا وأوروبا للسيطرة الكاملة", "ko": "완전한 제어를 위해 프랑스와 유럽에서 데이터 호스팅 보장", "nl": "Garandeer gegevenshosting in Frankrijk en Europa voor totale controle"},
    "confidentiality": {"en": "Confidentiality", "fr": "Confidentialité", "es": "Confidencialidad", "zh": "机密性", "ja": "機密性", "it": "Riservatezza", "de": "Vertraulichkeit", "pt": "Confidencialidade", "ru": "Конфиденциальность", "ar": "السرية", "ko": "기밀성", "nl": "Vertrouwelijkheid"},
    "protectDataEndToEnd": {"en": "Protect your data with end-to-end encryption and no resale to third parties", "fr": "Protéger vos données avec un chiffrement de bout en bout et sans revente à des tiers", "es": "Proteja sus datos con cifrado de extremo a extremo y sin reventa a terceros", "zh": "通过端到端加密保护您的数据，不向第三方转售", "ja": "エンドツーエンドの暗号化でデータを保護し、第三者への転売なし", "it": "Proteggi i tuoi dati con crittografia end-to-end e senza rivendita a terzi", "de": "Schützen Sie Ihre Daten mit Ende-zu-Ende-Verschlüsselung und ohne Weiterverkauf an Dritte", "pt": "Proteja seus dados com criptografia de ponta a ponta e sem revenda a terceiros", "ru": "Защитите свои данные сквозным шифрованием и без перепродажи третьим лицам", "ar": "احمِ بياناتك بالتشفير من طرف إلى طرف وبدون إعادة بيع لأطراف ثالثة", "ko": "엔드 투 엔드 암호화로 데이터를 보호하고 제3자에게 재판매하지 않습니다", "nl": "Bescherm uw gegevens met end-to-end-versleuteling en zonder doorverkoop aan derden"},
    "ecoResponsible": {"en": "Eco-responsible", "fr": "Éco-responsable", "es": "Eco-responsable", "zh": "生态责任", "ja": "環境に配慮した", "it": "Eco-responsabile", "de": "Umweltverantwortlich", "pt": "Eco-responsável", "ru": "Экологически ответственный", "ar": "مسؤول بيئيًا", "ko": "친환경", "nl": "Milieuvriendelijk"},
    "useGreenServers": {"en": "Use green servers and optimize our infrastructure to reduce our carbon footprint", "fr": "Utiliser des serveurs verts et optimiser notre infrastructure pour réduire notre empreinte carbone", "es": "Usar servidores verdes y optimizar nuestra infraestructura para reducir nuestra huella de carbono", "zh": "使用绿色服务器并优化我们的基础设施以减少碳足迹", "ja": "グリーンサーバーを使用し、インフラを最適化して炭素排出量を削減", "it": "Utilizzare server verdi e ottimizzare la nostra infrastruttura per ridurre la nostra impronta di carbonio", "de": "Verwenden Sie grüne Server und optimieren Sie unsere Infrastruktur, um unseren CO2-Fußabdruck zu reduzieren", "pt": "Use servidores verdes e otimize nossa infraestrutura para reduzir nossa pegada de carbono", "ru": "Используйте зеленые серверы и оптимизируйте нашу инфраструктуру, чтобы уменьшить наш углеродный след", "ar": "استخدم خوادم خضراء وحسّن بنيتنا التحتية لتقليل بصمتنا الكربونية", "ko": "탄소 발자국을 줄이기 위해 친환경 서버를 사용하고 인프라를 최적화합니다", "nl": "Gebruik groene servers en optimaliseer onze infrastructuur om onze ecologische voetafdruk te verkleinen"},
    "ourValues": {"en": "Our Values", "fr": "Nos Valeurs", "es": "Nuestros Valores", "zh": "我们的价值观", "ja": "私たちの価値観", "it": "I nostri Valori", "de": "Unsere Werte", "pt": "Nossos Valores", "ru": "Наши ценности", "ar": "قيمنا", "ko": "우리의 가치", "nl": "Onze Waarden"},
    "transparency": {"en": "Transparency", "fr": "Transparence", "es": "Transparencia", "zh": "透明度", "ja": "透明性", "it": "Trasparenza", "de": "Transparenz", "pt": "Transparência", "ru": "Прозрачность", "ar": "الشفافية", "ko": "투명성", "nl": "Transparantie"},
    "openCommunication": {"en": "We believe in open communication with our users. No hidden conditions, no data collection without your knowledge.", "fr": "Nous croyons en une communication ouverte avec nos utilisateurs. Pas de conditions cachées, pas de collecte de données à votre insu.", "es": "Creemos en una comunicación abierta con nuestros usuarios. Sin condiciones ocultas, sin recopilación de datos sin su conocimiento.", "zh": "我们相信与用户进行开放式沟通。没有隐藏条件，不在您不知情的情况下收集数据。", "ja": "ユーザーとのオープンなコミュニケーションを信じています。隠れた条件はなく、知らないうちにデータを収集することはありません。", "it": "Crediamo in una comunicazione aperta con i nostri utenti. Nessuna condizione nascosta, nessuna raccolta di dati a vostra insaputa.", "de": "Wir glauben an offene Kommunikation mit unseren Benutzern. Keine versteckten Bedingungen, keine Datenerfassung ohne Ihr Wissen.", "pt": "Acreditamos em comunicação aberta com nossos usuários. Sem condições ocultas, sem coleta de dados sem seu conhecimento.", "ru": "Мы верим в открытое общение с нашими пользователями. Никаких скрытых условий, никакого сбора данных без вашего ведома.", "ar": "نؤمن بالتواصل المفتوح مع مستخدمينا. لا شروط مخفية، لا جمع بيانات دون علمك.", "ko": "사용자와의 개방적인 의사소통을 믿습니다. 숨겨진 조건 없음, 귀하가 모르게 데이터를 수집하지 않습니다.", "nl": "We geloven in open communicatie met onze gebruikers. Geen verborgen voorwaarden, geen gegevensverzameling zonder uw medeweten."},
    "accessibility": {"en": "Accessibility", "fr": "Accessibilité", "es": "Accesibilidad", "zh": "可访问性", "ja": "アクセシビリティ", "it": "Accessibilità", "de": "Zugänglichkeit", "pt": "Acessibilidade", "ru": "Доступность", "ar": "إمكانية الوصول", "ko": "접근성", "nl": "Toegankelijkheid"},
    "fairPricing": {"en": "Fair pricing and a complete free offer to make digital accessible to everyone, individuals and businesses alike.", "fr": "Des tarifs justes et une offre gratuite complète pour rendre le numérique accessible à tous, particuliers comme entreprises.", "es": "Precios justos y una oferta gratuita completa para hacer el digital accesible a todos, tanto particulares como empresas.", "zh": "公平的定价和完整的免费服务，使数字服务对所有人、个人和企业都可访问。", "ja": "公正な価格設定と完全な無料オファーで、個人や企業を問わずすべての人にデジタルをアクセスしやすくします。", "it": "Prezzi equi e un'offerta gratuita completa per rendere il digitale accessibile a tutti, privati e aziende.", "de": "Faire Preise und ein vollständiges kostenloses Angebot, um das Digitale für alle zugänglich zu machen, sowohl für Privatpersonen als auch für Unternehmen.", "pt": "Preços justos e uma oferta gratuita completa para tornar o digital acessível a todos, particulares e empresas.", "ru": "Справедливые цены и полное бесплатное предложение, чтобы сделать цифровые технологии доступными для всех, как для частных лиц, так и для предприятий.", "ar": "أسعار عادلة وعرض مجاني كامل لجعل الرقمنة متاحة للجميع، الأفراد والشركات على حد سواء.", "ko": "개인과 기업 모두에게 디지털을 접근 가능하게 만들기 위한 공정한 가격과 완전한 무료 제공.", "nl": "Eerlijke prijzen en een volledig gratis aanbod om digitaal toegankelijk te maken voor iedereen, particulieren en bedrijven."},
    "performance": {"en": "Performance", "fr": "Performance", "es": "Rendimiento", "zh": "性能", "ja": "パフォーマンス", "it": "Prestazioni", "de": "Leistung", "pt": "Desempenho", "ru": "Производительность", "ar": "الأداء", "ko": "성능", "nl": "Prestatie"},
    "fastReliableTools": {"en": "Fast, reliable and available 24/7 tools with a latest generation cloud infrastructure.", "fr": "Des outils rapides, fiables et disponibles 24/7 avec une infrastructure cloud de dernière génération.", "es": "Herramientas rápidas, confiables y disponibles 24/7 con una infraestructura en la nube de última generación.", "zh": "快速、可靠且24/7可用的工具，配备最新一代云基础设施。", "ja": "最新世代のクラウドインフラストラクチャを備えた、高速で信頼性が高く24/7利用可能なツール。", "it": "Strumenti veloci, affidabili e disponibili 24/7 con un'infrastruttura cloud di ultima generazione.", "de": "Schnelle, zuverlässige und rund um die Uhr verfügbare Tools mit einer Cloud-Infrastruktur der neuesten Generation.", "pt": "Ferramentas rápidas, confiáveis e disponíveis 24/7 com uma infraestrutura em nuvem de última geração.", "ru": "Быстрые, надежные и доступные круглосуточно инструменты с облачной инфраструктурой последнего поколения.", "ar": "أدوات سريعة وموثوقة ومتاحة على مدار الساعة طوال أيام الأسبوع مع بنية تحتية سحابية من الجيل الأخير.", "ko": "최신 세대 클라우드 인프라를 갖춘 빠르고 안정적이며 24/7 사용 가능한 도구.", "nl": "Snelle, betrouwbare en 24/7 beschikbare tools met een cloudinfrastructuur van de nieuwste generatie."},
    "continuousInnovation": {"en": "Continuous Innovation", "fr": "Innovation Continue", "es": "Innovación Continua", "zh": "持续创新", "ja": "継続的なイノベーション", "it": "Innovazione Continua", "de": "Kontinuierliche Innovation", "pt": "Inovação Contínua", "ru": "Непрерывные инновации", "ar": "الابتكار المستمر", "ko": "지속적인 혁신", "nl": "Voortdurende Innovatie"},
    "constantlyImprove": {"en": "We constantly improve our services by listening to your feedback and integrating the latest technologies.", "fr": "Nous améliorons constamment nos services en écoutant vos retours et en intégrant les dernières technologies.", "es": "Mejoramos constantemente nuestros servicios escuchando sus comentarios e integrando las últimas tecnologías.", "zh": "我们通过倾听您的反馈并整合最新技术来不断改进我们的服务。", "ja": "お客様のフィードバックを聞き、最新の技術を統合することで、サービスを絶えず改善しています。", "it": "Miglioriamo costantemente i nostri servizi ascoltando il vostro feedback e integrando le ultime tecnologie.", "de": "Wir verbessern unsere Dienste ständig, indem wir auf Ihr Feedback hören und die neuesten Technologien integrieren.", "pt": "Melhoramos constantemente nossos serviços ouvindo seus comentários e integrando as mais recentes tecnologias.", "ru": "Мы постоянно улучшаем наши услуги, прислушиваясь к вашим отзывам и интегрируя новейшие технологии.", "ar": "نحسن خدماتنا باستمرار من خلال الاستماع إلى ملاحظاتك ودمج أحدث التقنيات.", "ko": "피드백을 듣고 최신 기술을 통합하여 서비스를 지속적으로 개선합니다.", "nl": "We verbeteren onze diensten voortdurend door naar uw feedback te luisteren en de nieuwste technologieën te integreren."},
    "whyOffice1789": {"en": "Why Office1789?", "fr": "Pourquoi Office1789 ?", "es": "¿Por qué Office1789?", "zh": "为什么选择Office1789？", "ja": "なぜOffice1789？", "it": "Perché Office1789?", "de": "Warum Office1789?", "pt": "Por que Office1789?", "ru": "Почему Office1789?", "ar": "لماذا Office1789؟", "ko": "왜 Office1789인가?", "nl": "Waarom Office1789?"},
    "statistics": {"en": "Statistics", "fr": "Statistiques", "es": "Estadísticas", "zh": "统计数据", "ja": "統計", "it": "Statistiche", "de": "Statistiken", "pt": "Estatísticas", "ru": "Статистика", "ar": "الإحصائيات", "ko": "통계", "nl": "Statistieken"},
    "availability": {"en": "Availability", "fr": "Disponibilité", "es": "Disponibilidad", "zh": "可用性", "ja": "可用性", "it": "Disponibilità", "de": "Verfügbarkeit", "pt": "Disponibilidade", "ru": "Доступность", "ar": "التوفر", "ko": "가용성", "nl": "Beschikbaarheid"},
    "french": {"en": "French", "fr": "Français", "es": "Francés", "zh": "法语", "ja": "フランス語", "it": "Francese", "de": "Französisch", "pt": "Francês", "ru": "Французский", "ar": "الفرنسية", "ko": "프랑스어", "nl": "Frans"},
    "advantages": {"en": "Advantages", "fr": "Avantages", "es": "Ventajas", "zh": "优势", "ja": "利点", "it": "Vantaggi", "de": "Vorteile", "pt": "Vantagens", "ru": "Преимущества", "ar": "المزايا", "ko": "장점", "nl": "Voordelen"},
    "noAds": {"en": "No ads", "fr": "Sans publicité", "es": "Sin publicidad", "zh": "无广告", "ja": "広告なし", "it": "Senza pubblicità", "de": "Ohne Werbung", "pt": "Sem anúncios", "ru": "Без рекламы", "ar": "بدون إعلانات", "ko": "광고 없음", "nl": "Geen advertenties"},
    "openSource": {"en": "Open Source", "fr": "Open Source", "es": "Código abierto", "zh": "开源", "ja": "オープンソース", "it": "Open Source", "de": "Open Source", "pt": "Código aberto", "ru": "Открытый исходный код", "ar": "مفتوح المصدر", "ko": "오픈 소스", "nl": "Open Source"},
    "reactiveSupport": {"en": "Responsive support", "fr": "Support réactif", "es": "Soporte receptivo", "zh": "响应式支持", "ja": "レスポンシブサポート", "it": "Supporto reattivo", "de": "Reaktive Unterstützung", "pt": "Suporte responsivo", "ru": "Оперативная поддержка", "ar": "دعم سريع الاستجابة", "ko": "빠른 지원", "nl": "Responsieve ondersteuning"},
    "easyMigration": {"en": "Easy migration", "fr": "Migration facile", "es": "Migración fácil", "zh": "轻松迁移", "ja": "簡単な移行", "it": "Migrazione facile", "de": "Einfache Migration", "pt": "Migração fácil", "ru": "Легкая миграция", "ar": "الهجرة السهلة", "ko": "쉬운 마이그레이션", "nl": "Gemakkelijke migratie"},
    "mobileApps": {"en": "Mobile apps", "fr": "Applications mobiles", "es": "Aplicaciones móviles", "zh": "移动应用", "ja": "モバイルアプリ", "it": "App mobili", "de": "Mobile Apps", "pt": "Aplicativos móveis", "ru": "Мобильные приложения", "ar": "تطبيقات الجوال", "ko": "모바일 앱", "nl": "Mobiele apps"},
    "thirdPartyIntegrations": {"en": "Third-party integrations", "fr": "Intégrations tierces", "es": "Integraciones de terceros", "zh": "第三方集成", "ja": "サードパーティ統合", "it": "Integrazioni di terze parti", "de": "Drittanbieter-Integrationen", "pt": "Integrações de terceiros", "ru": "Интеграции третьих сторон", "ar": "تكاملات الطرف الثالث", "ko": "타사 통합", "nl": "Integraties van derden"},
    "ourOffers": {"en": "Our Offers", "fr": "Nos Offres", "es": "Nuestras Ofertas", "zh": "我们的优惠", "ja": "私たちのオファー", "it": "Le nostre Offerte", "de": "Unsere Angebote", "pt": "Nossas Ofertas", "ru": "Наши предложения", "ar": "عروضنا", "ko": "우리의 제안", "nl": "Onze Aanbiedingen"},
    "readyToJoin": {"en": "Ready to join Office1789?", "fr": "Prêt à rejoindre Office1789 ?", "es": "¿Listo para unirse a Office1789?", "zh": "准备加入Office1789？", "ja": "Office1789に参加する準備はできましたか？", "it": "Pronto a unirti a Office1789?", "de": "Bereit, Office1789 beizutreten?", "pt": "Pronto para se juntar ao Office1789?", "ru": "Готовы присоединиться к Office1789?", "ar": "هل أنت مستعد للانضمام إلى Office1789؟", "ko": "Office1789에 가입할 준비가 되셨나요?", "nl": "Klaar om lid te worden van Office1789?"},
    "createAccountEnjoyServices": {"en": "Create your account for free and enjoy all our services", "fr": "Créez votre compte gratuitement et profitez de tous nos services", "es": "Cree su cuenta gratis y disfrute de todos nuestros servicios", "zh": "免费创建您的帐户并享受我们所有的服务", "ja": "無料でアカウントを作成し、すべてのサービスをお楽しみください", "it": "Crea il tuo account gratuitamente e goditi tutti i nostri servizi", "de": "Erstellen Sie kostenlos Ihr Konto und genießen Sie alle unsere Dienste", "pt": "Crie sua conta gratuitamente e aproveite todos os nossos serviços", "ru": "Создайте свою учетную запись бесплатно и наслаждайтесь всеми нашими услугами", "ar": "أنشئ حسابك مجانًا واستمتع بجميع خدماتنا", "ko": "무료로 계정을 만들고 모든 서비스를 즐기세요", "nl": "Maak gratis uw account aan en geniet van al onze diensten"},
    
    # === STORAGE & QUOTA ===
    "used": {"en": "used", "fr": "utilisés", "es": "utilizados", "zh": "已使用", "ja": "使用済み", "it": "utilizzati", "de": "verwendet", "pt": "usados", "ru": "использовано", "ar": "مستخدم", "ko": "사용됨", "nl": "gebruikt"},
    "unlimited": {"en": "Unlimited", "fr": "Illimité", "es": "Ilimitado", "zh": "无限", "ja": "無制限", "it": "Illimitato", "de": "Unbegrenzt", "pt": "Ilimitado", "ru": "Неограниченно", "ar": "غير محدود", "ko": "무제한", "nl": "Onbeperkt"},
    "quotaExceeded": {"en": "Quota exceeded! Delete files to free up space.", "fr": "Quota dépassé ! Supprimez des fichiers pour libérer de l'espace.", "es": "¡Cuota excedida! Elimine archivos para liberar espacio.", "zh": "配额已超！删除文件以释放空间。", "ja": "クォータを超えました！スペースを解放するためにファイルを削除してください。", "it": "Quota superata! Elimina i file per liberare spazio.", "de": "Kontingent überschritten! Löschen Sie Dateien, um Speicherplatz freizugeben.", "pt": "Cota excedida! Exclua arquivos para liberar espaço.", "ru": "Квота превышена! Удалите файлы, чтобы освободить место.", "ar": "تم تجاوز الحصة! احذف الملفات لتحرير المساحة.", "ko": "할당량 초과! 공간을 확보하려면 파일을 삭제하세요.", "nl": "Quotum overschreden! Verwijder bestanden om ruimte vrij te maken."},
    "almostFullUpgrade": {"en": "Space almost full. Consider upgrading your offer.", "fr": "Espace presque plein. Pensez à améliorer votre offre.", "es": "Espacio casi lleno. Considere mejorar su oferta.", "zh": "空间几乎已满。考虑升级您的套餐。", "ja": "スペースがほぼいっぱいです。オファーのアップグレードを検討してください。", "it": "Spazio quasi pieno. Considera di aggiornare la tua offerta.", "de": "Speicher fast voll. Erwägen Sie ein Upgrade Ihres Angebots.", "pt": "Espaço quase cheio. Considere atualizar sua oferta.", "ru": "Место почти заполнено. Рассмотрите возможность обновления вашего предложения.", "ar": "المساحة ممتلئة تقريبًا. فكر في ترقية عرضك.", "ko": "공간이 거의 가득 찼습니다. 오퍼 업그레이드를 고려하세요.", "nl": "Ruimte bijna vol. Overweeg uw aanbod te upgraden."},
    
    # === CALENDAR VIEW ===
    "calendarOffice1789": {"en": "Office1789 Calendar", "fr": "Calendrier Office1789", "es": "Calendario Office1789", "zh": "Office1789日历", "ja": "Office1789カレンダー", "it": "Calendario Office1789", "de": "Office1789 Kalender", "pt": "Calendário Office1789", "ru": "Календарь Office1789", "ar": "تقويم Office1789", "ko": "Office1789 캘린더", "nl": "Office1789 Agenda"},
    "organizeAppointments": {"en": "Organize your appointments and events", "fr": "Organisez vos rendez-vous et événements", "es": "Organice sus citas y eventos", "zh": "组织您的约会和活动", "ja": "予定とイベントを整理", "it": "Organizza i tuoi appuntamenti ed eventi", "de": "Organisieren Sie Ihre Termine und Veranstaltungen", "pt": "Organize seus compromissos e eventos", "ru": "Организуйте свои встречи и события", "ar": "نظم مواعيدك وأحداثك", "ko": "약속과 이벤트를 정리하세요", "nl": "Organiseer uw afspraken en evenementen"},
    "addEvent": {"en": "Add an event", "fr": "Ajouter un événement", "es": "Agregar un evento", "zh": "添加活动", "ja": "イベントを追加", "it": "Aggiungi un evento", "de": "Ereignis hinzufügen", "pt": "Adicionar um evento", "ru": "Добавить событие", "ar": "إضافة حدث", "ko": "이벤트 추가", "nl": "Evenement toevoegen"},
    "newEvent": {"en": "New Event", "fr": "Nouvel Événement", "es": "Nuevo Evento", "zh": "新活动", "ja": "新しいイベント", "it": "Nuovo Evento", "de": "Neues Ereignis", "pt": "Novo Evento", "ru": "Новое событие", "ar": "حدث جديد", "ko": "새 이벤트", "nl": "Nieuw Evenement"},
    "title": {"en": "Title", "fr": "Titre", "es": "Título", "zh": "标题", "ja": "タイトル", "it": "Titolo", "de": "Titel", "pt": "Título", "ru": "Заголовок", "ar": "العنوان", "ko": "제목", "nl": "Titel"},
    "eventTitle": {"en": "Event title", "fr": "Titre de l'événement", "es": "Título del evento", "zh": "活动标题", "ja": "イベントタイトル", "it": "Titolo dell'evento", "de": "Ereignistitel", "pt": "Título do evento", "ru": "Название события", "ar": "عنوان الحدث", "ko": "이벤트 제목", "nl": "Evenementtitel"},
    "date": {"en": "Date", "fr": "Date", "es": "Fecha", "zh": "日期", "ja": "日付", "it": "Data", "de": "Datum", "pt": "Data", "ru": "Дата", "ar": "التاريخ", "ko": "날짜", "nl": "Datum"},
    "startTime": {"en": "Start time", "fr": "Heure de début", "es": "Hora de inicio", "zh": "开始时间", "ja": "開始時刻", "it": "Ora di inizio", "de": "Startzeit", "pt": "Hora de início", "ru": "Время начала", "ar": "وقت البداية", "ko": "시작 시간", "nl": "Starttijd"},
    "endTime": {"en": "End time", "fr": "Heure de fin", "es": "Hora de finalización", "zh": "结束时间", "ja": "終了時刻", "it": "Ora di fine", "de": "Endzeit", "pt": "Hora de término", "ru": "Время окончания", "ar": "وقت الانتهاء", "ko": "종료 시간", "nl": "Eindtijd"},
    "location": {"en": "Location", "fr": "Lieu", "es": "Ubicación", "zh": "地点", "ja": "場所", "it": "Luogo", "de": "Ort", "pt": "Local", "ru": "Место", "ar": "الموقع", "ko": "위치", "nl": "Locatie"},
    "eventLocation": {"en": "Event location", "fr": "Lieu de l'événement", "es": "Ubicación del evento", "zh": "活动地点", "ja": "イベントの場所", "it": "Luogo dell'evento", "de": "Veranstaltungsort", "pt": "Local do evento", "ru": "Место проведения мероприятия", "ar": "موقع الحدث", "ko": "이벤트 위치", "nl": "Evenementlocatie"},
    "description": {"en": "Description", "fr": "Description", "es": "Descripción", "zh": "描述", "ja": "説明", "it": "Descrizione", "de": "Beschreibung", "pt": "Descrição", "ru": "Описание", "ar": "الوصف", "ko": "설명", "nl": "Beschrijving"},
    "eventDescription": {"en": "Event description", "fr": "Description de l'événement", "es": "Descripción del evento", "zh": "活动描述", "ja": "イベントの説明", "it": "Descrizione dell'evento", "de": "Ereignisbeschreibung", "pt": "Descrição do evento", "ru": "Описание события", "ar": "وصف الحدث", "ko": "이벤트 설명", "nl": "Evenementbeschrijving"},
    "add": {"en": "Add", "fr": "Ajouter", "es": "Agregar", "zh": "添加", "ja": "追加", "it": "Aggiungi", "de": "Hinzufügen", "pt": "Adicionar", "ru": "Добавить", "ar": "إضافة", "ko": "추가", "nl": "Toevoegen"},
    "deleteEvent": {"en": "Delete event", "fr": "Supprimer l'événement", "es": "Eliminar evento", "zh": "删除活动", "ja": "イベントを削除", "it": "Elimina evento", "de": "Ereignis löschen", "pt": "Excluir evento", "ru": "Удалить событие", "ar": "حذف الحدث", "ko": "이벤트 삭제", "nl": "Evenement verwijderen"},
    "confirmDeleteEvent": {"en": "Are you sure you want to delete the event", "fr": "Êtes-vous sûr de vouloir supprimer l'événement", "es": "¿Está seguro de que desea eliminar el evento", "zh": "您确定要删除活动吗", "ja": "イベントを削除してもよろしいですか", "it": "Sei sicuro di voler eliminare l'evento", "de": "Sind Sie sicher, dass Sie das Ereignis löschen möchten", "pt": "Tem certeza de que deseja excluir o evento", "ru": "Вы уверены, что хотите удалить событие", "ar": "هل أنت متأكد من أنك تريد حذف الحدث", "ko": "이벤트를 삭제하시겠습니까", "nl": "Weet u zeker dat u het evenement wilt verwijderen"},
    "delete": {"en": "Delete", "fr": "Supprimer", "es": "Eliminar", "zh": "删除", "ja": "削除", "it": "Elimina", "de": "Löschen", "pt": "Excluir", "ru": "Удалить", "ar": "حذف", "ko": "삭제", "nl": "Verwijderen"},
    
    # === ADMIN PANEL ===
    "adminPanel": {"en": "Admin Panel", "fr": "Panel Administrateur", "es": "Panel de Administrador", "zh": "管理面板", "ja": "管理パネル", "it": "Pannello Amministratore", "de": "Admin-Panel", "pt": "Painel de Administrador", "ru": "Панель администратора", "ar": "لوحة الإدارة", "ko": "관리자 패널", "nl": "Beheerderspaneel"},
    "users": {"en": "Users", "fr": "Utilisateurs", "es": "Usuarios", "zh": "用户", "ja": "ユーザー", "it": "Utenti", "de": "Benutzer", "pt": "Usuários", "ru": "Пользователи", "ar": "المستخدمون", "ko": "사용자", "nl": "Gebruikers"},
    "verifiedEmails": {"en": "Verified emails", "fr": "Emails vérifiés", "es": "Correos electrónicos verificados", "zh": "已验证的电子邮件", "ja": "確認済みメール", "it": "Email verificate", "de": "Verifizierte E-Mails", "pt": "E-mails verificados", "ru": "Проверенные электронные письма", "ar": "رسائل البريد الإلكتروني المعتمدة", "ko": "인증된 이메일", "nl": "Geverifieerde e-mails"},
    "verifiedPhones": {"en": "Verified phones", "fr": "Téléphones vérifiés", "es": "Teléfonos verificados", "zh": "已验证的电话", "ja": "確認済み電話", "it": "Telefoni verificati", "de": "Verifizierte Telefone", "pt": "Telefones verificados", "ru": "Проверенные телефоны", "ar": "الهواتف المعتمدة", "ko": "인증된 전화", "nl": "Geverifieerde telefoons"},
    "withoutVerifiedContact": {"en": "Without verified contact", "fr": "Sans contact vérifié", "es": "Sin contacto verificado", "zh": "没有已验证的联系人", "ja": "確認済みの連絡先なし", "it": "Senza contatto verificato", "de": "Ohne verifizierten Kontakt", "pt": "Sem contato verificado", "ru": "Без проверенного контакта", "ar": "بدون جهة اتصال معتمدة", "ko": "인증된 연락처 없음", "nl": "Zonder geverifieerd contact"},
    "storedFiles": {"en": "Stored files", "fr": "Fichiers stockés", "es": "Archivos almacenados", "zh": "存储的文件", "ja": "保存されたファイル", "it": "File archiviati", "de": "Gespeicherte Dateien", "pt": "Arquivos armazenados", "ru": "Сохраненные файлы", "ar": "الملفات المخزنة", "ko": "저장된 파일", "nl": "Opgeslagen bestanden"},
    "calendarEvents": {"en": "Calendar events", "fr": "Événements calendrier", "es": "Eventos de calendario", "zh": "日历事件", "ja": "カレンダーイベント", "it": "Eventi del calendario", "de": "Kalenderereignisse", "pt": "Eventos de calendário", "ru": "События календаря", "ar": "أحداث التقويم", "ko": "캘린더 이벤트", "nl": "Agenda-evenementen"},
    "verificationDistribution": {"en": "Verification distribution", "fr": "Distribution des vérifications", "es": "Distribución de verificaciones", "zh": "验证分布", "ja": "確認の分布", "it": "Distribuzione delle verifiche", "de": "Verifizierungsverteilung", "pt": "Distribuição de verificações", "ru": "Распределение проверок", "ar": "توزيع التحقق", "ko": "인증 분포", "nl": "Verificatieverdeling"},
    "subscriptions": {"en": "Subscriptions", "fr": "Abonnements", "es": "Suscripciones", "zh": "订阅", "ja": "サブスクリプション", "it": "Abbonamenti", "de": "Abonnements", "pt": "Assinaturas", "ru": "Подписки", "ar": "الاشتراكات", "ko": "구독", "nl": "Abonnementen"},
    "userManagement": {"en": "User Management", "fr": "Gestion des utilisateurs", "es": "Gestión de usuarios", "zh": "用户管理", "ja": "ユーザー管理", "it": "Gestione utenti", "de": "Benutzerverwaltung", "pt": "Gerenciamento de usuários", "ru": "Управление пользователями", "ar": "إدارة المستخدمين", "ko": "사용자 관리", "nl": "Gebruikersbeheer"},
    "searchUser": {"en": "Search a user...", "fr": "Rechercher un utilisateur...", "es": "Buscar un usuario...", "zh": "搜索用户...", "ja": "ユーザーを検索...", "it": "Cerca un utente...", "de": "Benutzer suchen...", "pt": "Pesquisar um usuário...", "ru": "Поиск пользователя...", "ar": "البحث عن مستخدم...", "ko": "사용자 검색...", "nl": "Zoek een gebruiker..."},
    "recoveryEmail": {"en": "Recovery Email", "fr": "Recovery Email", "es": "Correo de recuperación", "zh": "恢复邮箱", "ja": "回復用メール", "it": "Email di recupero", "de": "Wiederherstellungs-E-Mail", "pt": "E-mail de recuperação", "ru": "Резервная электронная почта", "ar": "البريد الإلكتروني للاسترداد", "ko": "복구 이메일", "nl": "Herstel-e-mail"},
    "phone": {"en": "Phone", "fr": "Téléphone", "es": "Teléfono", "zh": "电话", "ja": "電話", "it": "Telefono", "de": "Telefon", "pt": "Telefone", "ru": "Телефон", "ar": "الهاتف", "ko": "전화", "nl": "Telefoon"},
    "role": {"en": "Role", "fr": "Rôle", "es": "Rol", "zh": "角色", "ja": "役割", "it": "Ruolo", "de": "Rolle", "pt": "Função", "ru": "Роль", "ar": "الدور", "ko": "역할", "nl": "Rol"},
    "offer": {"en": "Offer", "fr": "Offre", "es": "Oferta", "zh": "优惠", "ja": "オファー", "it": "Offerta", "de": "Angebot", "pt": "Oferta", "ru": "Предложение", "ar": "العرض", "ko": "제안", "nl": "Aanbod"},
    "registeredOn": {"en": "Registered on", "fr": "Inscrit le", "es": "Registrado el", "zh": "注册于", "ja": "登録日", "it": "Registrato il", "de": "Registriert am", "pt": "Registrado em", "ru": "Зарегистрирован", "ar": "مسجل في", "ko": "등록일", "nl": "Geregistreerd op"},
    "actions": {"en": "Actions", "fr": "Actions", "es": "Acciones", "zh": "操作", "ja": "アクション", "it": "Azioni", "de": "Aktionen", "pt": "Ações", "ru": "Действия", "ar": "الإجراءات", "ko": "작업", "nl": "Acties"},
    "demote": {"en": "Demote", "fr": "Rétrograder", "es": "Degradar", "zh": "降级", "ja": "降格", "it": "Retrocedere", "de": "Herabstufen", "pt": "Rebaixar", "ru": "Понизить", "ar": "تخفيض الرتبة", "ko": "강등", "nl": "Degraderen"},
    "promote": {"en": "Promote", "fr": "Promouvoir", "es": "Promover", "zh": "升级", "ja": "昇格", "it": "Promuovere", "de": "Befördern", "pt": "Promover", "ru": "Повысить", "ar": "ترقية", "ko": "승격", "nl": "Promoveren"},
    
    # === DRIVE VIEW ===
    "searchPlaceholder": {"en": "Search...", "fr": "Rechercher...", "es": "Buscar...", "zh": "搜索...", "ja": "検索...", "it": "Cerca...", "de": "Suchen...", "pt": "Pesquisar...", "ru": "Поиск...", "ar": "بحث...", "ko": "검색...", "nl": "Zoeken..."},
    "multipleSelection": {"en": "Multiple Selection", "fr": "Sélection Multiple", "es": "Selección Múltiple", "zh": "多选", "ja": "複数選択", "it": "Selezione Multipla", "de": "Mehrfachauswahl", "pt": "Seleção Múltipla", "ru": "Множественный выбор", "ar": "اختيار متعدد", "ko": "다중 선택", "nl": "Meervoudige Selectie"},
    "selectAllLabel": {"en": "Select all :", "fr": "Tout sélectionner :", "es": "Seleccionar todo :", "zh": "全选 :", "ja": "すべて選択 :", "it": "Seleziona tutto :", "de": "Alle auswählen :", "pt": "Selecionar tudo :", "ru": "Выбрать все :", "ar": "تحديد الكل :", "ko": "모두 선택 :", "nl": "Alles selecteren :"},
    "moveToTrash": {"en": "Move to trash", "fr": "Mettre à la corbeille", "es": "Mover a la papelera", "zh": "移至回收站", "ja": "ゴミ箱に移動", "it": "Sposta nel cestino", "de": "In den Papierkorb verschieben", "pt": "Mover para a lixeira", "ru": "Переместить в корзину", "ar": "نقل إلى سلة المهملات", "ko": "휴지통으로 이동", "nl": "Naar prullenbak verplaatsen"},
    "deletePermanently": {"en": "Delete permanently", "fr": "Supprimer définitivement", "es": "Eliminar permanentemente", "zh": "永久删除", "ja": "完全に削除", "it": "Elimina definitivamente", "de": "Dauerhaft löschen", "pt": "Excluir permanentemente", "ru": "Удалить навсегда", "ar": "حذف نهائي", "ko": "영구 삭제", "nl": "Permanent verwijderen"},
    "moveFiles": {"en": "Move files", "fr": "Déplacer fichiers", "es": "Mover archivos", "zh": "移动文件", "ja": "ファイルを移動", "it": "Sposta file", "de": "Dateien verschieben", "pt": "Mover arquivos", "ru": "Переместить файлы", "ar": "نقل الملفات", "ko": "파일 이동", "nl": "Bestanden verplaatsen"},
    "download": {"en": "Download", "fr": "Télécharger", "es": "Descargar", "zh": "下载", "ja": "ダウンロード", "it": "Scarica", "de": "Herunterladen", "pt": "Baixar", "ru": "Скачать", "ar": "تحميل", "ko": "다운로드", "nl": "Downloaden"},
    "selectFirst": {"en": "Select 1st", "fr": "Sélectionner 1er", "es": "Seleccionar 1º", "zh": "选择第1个", "ja": "1番目を選択", "it": "Seleziona 1°", "de": "1. auswählen", "pt": "Selecionar 1º", "ru": "Выбрать 1-й", "ar": "تحديد الأول", "ko": "첫 번째 선택", "nl": "Selecteer 1e"},
    "clear": {"en": "Clear", "fr": "Effacer", "es": "Borrar", "zh": "清除", "ja": "クリア", "it": "Cancella", "de": "Löschen", "pt": "Limpar", "ru": "Очистить", "ar": "مسح", "ko": "지우기", "nl": "Wissen"},
    "goUp": {"en": "Go up", "fr": "Remonter", "es": "Subir", "zh": "向上", "ja": "上へ", "it": "Risali", "de": "Nach oben", "pt": "Subir", "ru": "Вверх", "ar": "الصعود", "ko": "위로", "nl": "Omhoog"},
    "noFilesHere": {"en": "No files here", "fr": "Aucun fichier ici", "es": "No hay archivos aquí", "zh": "这里没有文件", "ja": "ここにファイルはありません", "it": "Nessun file qui", "de": "Keine Dateien hier", "pt": "Nenhum arquivo aqui", "ru": "Здесь нет файлов", "ar": "لا توجد ملفات هنا", "ko": "여기에 파일이 없습니다", "nl": "Geen bestanden hier"},
    "dragDropInfo": {"en": "Drag and drop a file/folder here or click on", "fr": "Glisse-dépose un fichier/dossier ici ou clique sur", "es": "Arrastra y suelta un archivo/carpeta aquí o haz clic en", "zh": "将文件/文件夹拖放到此处或点击", "ja": "ファイル/フォルダをここにドラッグ＆ドロップするか、クリック", "it": "Trascina e rilascia un file/cartella qui o clicca su", "de": "Ziehen Sie eine Datei/einen Ordner hierher oder klicken Sie auf", "pt": "Arraste e solte um arquivo/pasta aqui ou clique em", "ru": "Перетащите файл/папку сюда или нажмите на", "ar": "اسحب وأفلت ملفًا/مجلدًا هنا أو انقر على", "ko": "파일/폴더를 여기로 드래그 앤 드롭하거나 클릭", "nl": "Sleep een bestand/map hierheen of klik op"},
    "upload": {"en": "Upload", "fr": "Upload", "es": "Subir", "zh": "上传", "ja": "アップロード", "it": "Carica", "de": "Hochladen", "pt": "Enviar", "ru": "Загрузить", "ar": "رفع", "ko": "업로드", "nl": "Uploaden"},
    "folder": {"en": "Folder", "fr": "Dossier", "es": "Carpeta", "zh": "文件夹", "ja": "フォルダ", "it": "Cartella", "de": "Ordner", "pt": "Pasta", "ru": "Папка", "ar": "مجلد", "ko": "폴더", "nl": "Map"},
    "thisActionIsIrreversible": {"en": "This action is irreversible.", "fr": "Cette action est irréversible.", "es": "Esta acción es irreversible.", "zh": "此操作不可逆。", "ja": "この操作は元に戻せません。", "it": "Questa azione è irreversibile.", "de": "Diese Aktion ist irreversibel.", "pt": "Esta ação é irreversível.", "ru": "Это действие необратимо.", "ar": "هذا الإجراء لا رجعة فيه.", "ko": "이 작업은 되돌릴 수 없습니다.", "nl": "Deze actie is onomkeerbaar."},
    "cancelAll": {"en": "Cancel all", "fr": "Annuler tout", "es": "Cancelar todo", "zh": "取消全部", "ja": "すべてキャンセル", "it": "Annulla tutto", "de": "Alle abbrechen", "pt": "Cancelar tudo", "ru": "Отменить все", "ar": "إلغاء الكل", "ko": "모두 취소", "nl": "Alles annuleren"},
    "cancel": {"en": "Cancel", "fr": "Annuler", "es": "Cancelar", "zh": "取消", "ja": "キャンセル", "it": "Annulla", "de": "Abbrechen", "pt": "Cancelar", "ru": "Отмена", "ar": "إلغاء", "ko": "취소", "nl": "Annuleren"},
    "close": {"en": "Close", "fr": "Fermer", "es": "Cerrar", "zh": "关闭", "ja": "閉じる", "it": "Chiudi", "de": "Schließen", "pt": "Fechar", "ru": "Закрыть", "ar": "إغلاق", "ko": "닫기", "nl": "Sluiten"},
    "rename": {"en": "Rename", "fr": "Renommer", "es": "Renombrar", "zh": "重命名", "ja": "名前を変更", "it": "Rinomina", "de": "Umbenennen", "pt": "Renomear", "ru": "Переименовать", "ar": "إعادة تسمية", "ko": "이름 바꾸기", "nl": "Hernoemen"},
    "newFolder": {"en": "New Folder", "fr": "Nouveau Dossier", "es": "Nueva Carpeta", "zh": "新文件夹", "ja": "新しいフォルダ", "it": "Nuova Cartella", "de": "Neuer Ordner", "pt": "Nova Pasta", "ru": "Новая папка", "ar": "مجلد جديد", "ko": "새 폴더", "nl": "Nieuwe Map"},
    "newFile": {"en": "New File", "fr": "Nouveau Fichier", "es": "Nuevo Archivo", "zh": "新文件", "ja": "新しいファイル", "it": "Nuovo File", "de": "Neue Datei", "pt": "Novo Arquivo", "ru": "Новый файл", "ar": "ملف جديد", "ko": "새 파일", "nl": "Nieuw Bestand"},
    "folderName": {"en": "Folder name", "fr": "Nom du dossier", "es": "Nombre de la carpeta", "zh": "文件夹名称", "ja": "フォルダ名", "it": "Nome cartella", "de": "Ordnername", "pt": "Nome da pasta", "ru": "Имя папки", "ar": "اسم المجلد", "ko": "폴더 이름", "nl": "Mapnaam"},
    "fileName": {"en": "File name", "fr": "Nom du fichier", "es": "Nombre del archivo", "zh": "文件名", "ja": "ファイル名", "it": "Nome file", "de": "Dateiname", "pt": "Nome do arquivo", "ru": "Имя файла", "ar": "اسم الملف", "ko": "파일 이름", "nl": "Bestandsnaam"},
    "create": {"en": "Create", "fr": "Créer", "es": "Crear", "zh": "创建", "ja": "作成", "it": "Crea", "de": "Erstellen", "pt": "Criar", "ru": "Создать", "ar": "إنشاء", "ko": "생성", "nl": "Aanmaken"},
    "share": {"en": "Share", "fr": "Partager", "es": "Compartir", "zh": "分享", "ja": "共有", "it": "Condividi", "de": "Teilen", "pt": "Compartilhar", "ru": "Поделиться", "ar": "مشاركة", "ko": "공유", "nl": "Delen"},
    "selectFileToPreview": {"en": "Select a file to view the preview", "fr": "Sélectionne un fichier pour voir l'aperçu", "es": "Selecciona un archivo para ver la vista previa", "zh": "选择文件以查看预览", "ja": "プレビューを表示するファイルを選択", "it": "Seleziona un file per visualizzare l'anteprima", "de": "Wählen Sie eine Datei aus, um die Vorschau anzuzeigen", "pt": "Selecione um arquivo para visualizar a prévia", "ru": "Выберите файл для просмотра", "ar": "حدد ملفًا لعرض المعاينة", "ko": "미리보기를 보려면 파일을 선택하세요", "nl": "Selecteer een bestand om de voorvertoning te bekijken"},
    "open": {"en": "Open", "fr": "Ouvrir", "es": "Abrir", "zh": "打开", "ja": "開く", "it": "Apri", "de": "Öffnen", "pt": "Abrir", "ru": "Открыть", "ar": "فتح", "ko": "열기", "nl": "Openen"},
    "moveFile": {"en": "Move file", "fr": "Déplacer fichier", "es": "Mover archivo", "zh": "移动文件", "ja": "ファイルを移動", "it": "Sposta file", "de": "Datei verschieben", "pt": "Mover arquivo", "ru": "Переместить файл", "ar": "نقل الملف", "ko": "파일 이동", "nl": "Bestand verplaatsen"},
    "restore": {"en": "Restore", "fr": "Restaurer", "es": "Restaurar", "zh": "恢复", "ja": "復元", "it": "Ripristina", "de": "Wiederherstellen", "pt": "Restaurar", "ru": "Восстановить", "ar": "استعادة", "ko": "복원", "nl": "Herstellen"},
    "uploadsInProgress": {"en": "Uploads in progress", "fr": "Uploads en cours", "es": "Subidas en curso", "zh": "正在上传", "ja": "アップロード中", "it": "Caricamenti in corso", "de": "Uploads laufen", "pt": "Envios em andamento", "ru": "Загрузка в процессе", "ar": "التحميلات جارية", "ko": "업로드 진행 중", "nl": "Uploads bezig"},
    "global": {"en": "Global", "fr": "Global", "es": "Global", "zh": "全局", "ja": "全体", "it": "Globale", "de": "Global", "pt": "Global", "ru": "Общий", "ar": "عام", "ko": "전체", "nl": "Globaal"},
    "sending": {"en": "Sending...", "fr": "Envoi…", "es": "Enviando...", "zh": "发送中...", "ja": "送信中...", "it": "Invio...", "de": "Senden...", "pt": "Enviando...", "ru": "Отправка...", "ar": "جاري الإرسال...", "ko": "전송 중...", "nl": "Verzenden..."},
    "completed": {"en": "Completed", "fr": "Terminé", "es": "Completado", "zh": "已完成", "ja": "完了", "it": "Completato", "de": "Abgeschlossen", "pt": "Concluído", "ru": "Завершено", "ar": "مكتمل", "ko": "완료", "nl": "Voltooid"},
    "error": {"en": "Error", "fr": "Erreur", "es": "Error", "zh": "错误", "ja": "エラー", "it": "Errore", "de": "Fehler", "pt": "Erro", "ru": "Ошибка", "ar": "خطأ", "ko": "오류", "nl": "Fout"},
    "cancelled": {"en": "Cancelled", "fr": "Annulé", "es": "Cancelado", "zh": "已取消", "ja": "キャンセル済み", "it": "Annullato", "de": "Abgebrochen", "pt": "Cancelado", "ru": "Отменено", "ar": "ملغى", "ko": "취소됨", "nl": "Geannuleerd"},
    "retry": {"en": "Retry", "fr": "Réessayer", "es": "Reintentar", "zh": "重试", "ja": "再試行", "it": "Riprova", "de": "Wiederholen", "pt": "Tentar novamente", "ru": "Повторить", "ar": "إعادة المحاولة", "ko": "재시도", "nl": "Opnieuw proberen"},
    "fileType": {"en": "File type", "fr": "Type de fichier", "es": "Tipo de archivo", "zh": "文件类型", "ja": "ファイルタイプ", "it": "Tipo di file", "de": "Dateityp", "pt": "Tipo de arquivo", "ru": "Тип файла", "ar": "نوع الملف", "ko": "파일 유형", "nl": "Bestandstype"},
    "wordDocument": {"en": "Word Document", "fr": "Document Word", "es": "Documento Word", "zh": "Word 文档", "ja": "Word ドキュメント", "it": "Documento Word", "de": "Word-Dokument", "pt": "Documento Word", "ru": "Документ Word", "ar": "مستند Word", "ko": "Word 문서", "nl": "Word-document"},
    "excelSheet": {"en": "Excel Sheet", "fr": "Feuille Excel", "es": "Hoja Excel", "zh": "Excel 表格", "ja": "Excel シート", "it": "Foglio Excel", "de": "Excel-Tabelle", "pt": "Planilha Excel", "ru": "Таблица Excel", "ar": "ورقة Excel", "ko": "Excel 시트", "nl": "Excel-blad"},
    "powerpointPresentation": {"en": "PowerPoint Presentation", "fr": "Présentation PowerPoint", "es": "Presentación PowerPoint", "zh": "PowerPoint 演示文稿", "ja": "PowerPoint プレゼンテーション", "it": "Presentazione PowerPoint", "de": "PowerPoint-Präsentation", "pt": "Apresentação PowerPoint", "ru": "Презентация PowerPoint", "ar": "عرض PowerPoint", "ko": "PowerPoint 프레젠테이션", "nl": "PowerPoint-presentatie"},
    "fileNameNoExtension": {"en": "File name (without extension)", "fr": "Nom du fichier (sans extension)", "es": "Nombre del archivo (sin extensión)", "zh": "文件名（不含扩展名）", "ja": "ファイル名（拡張子なし）", "it": "Nome file (senza estensione)", "de": "Dateiname (ohne Erweiterung)", "pt": "Nome do arquivo (sem extensão)", "ru": "Имя файла (без расширения)", "ar": "اسم الملف (بدون امتداد)", "ko": "파일 이름 (확장자 제외)", "nl": "Bestandsnaam (zonder extensie)"},
    "createAndOpen": {"en": "Create and open", "fr": "Créer et ouvrir", "es": "Crear y abrir", "zh": "创建并打开", "ja": "作成して開く", "it": "Crea e apri", "de": "Erstellen und öffnen", "pt": "Criar e abrir", "ru": "Создать и открыть", "ar": "إنشاء وفتح", "ko": "생성 및 열기", "nl": "Aanmaken en openen"},
    "validate": {"en": "Validate", "fr": "Valider", "es": "Validar", "zh": "验证", "ja": "検証", "it": "Valida", "de": "Validieren", "pt": "Validar", "ru": "Проверить", "ar": "التحقق", "ko": "검증", "nl": "Valideren"},
}

def load_translations() -> Dict:
    """Charge le fichier traduction.json existant"""
    traduction_file = Path(__file__).parent / "webfront2" / "src" / "traduction.json"
    with open(traduction_file, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_translations(data: Dict):
    """Sauvegarde le fichier traduction.json"""
    traduction_file = Path(__file__).parent / "webfront2" / "src" / "traduction.json"
    with open(traduction_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=4, ensure_ascii=False)

def ensure_all_languages_exist(data: Dict) -> Dict:
    """S'assure que toutes les langues existent dans la structure"""
    for lang_code in LANGUAGES.keys():
        if lang_code not in data:
            data[lang_code] = {}
    return data

def add_missing_translations(data: Dict) -> Dict:
    """Ajoute toutes les traductions manquantes pour toutes les langues"""
    
    # S'assurer que toutes les langues existent
    data = ensure_all_languages_exist(data)
    
    # Pour chaque clé dans TRANSLATIONS
    for key, translations in TRANSLATIONS.items():
        # Pour chaque langue
        for lang_code in LANGUAGES.keys():
            # Si la clé n'existe pas dans cette langue, l'ajouter
            if key not in data[lang_code]:
                # Utiliser la traduction de TRANSLATIONS si disponible
                if lang_code in translations:
                    data[lang_code][key] = translations[lang_code]
                # Sinon, utiliser l'anglais comme fallback
                elif lang_code in data and key in data['en']:
                    data[lang_code][key] = data['en'][key]
    
    # Ajouter les clés existantes dans 'en' qui ne sont pas dans TRANSLATIONS
    if 'en' in data:
        for key in data['en'].keys():
            if key not in TRANSLATIONS:
                # Copier cette clé dans toutes les langues si elle n'existe pas
                for lang_code in LANGUAGES.keys():
                    if key not in data[lang_code]:
                        data[lang_code][key] = data['en'][key]
    
    return data

def main():
    print("🌍 Mise à jour complète des traductions Office1789")
    print("=" * 60)
    
    # Charger les traductions existantes
    print("\n📖 Chargement du fichier traduction.json...")
    data = load_translations()
    
    # Ajouter toutes les traductions manquantes
    print("\n✨ Ajout des traductions manquantes...")
    data = add_missing_translations(data)
    
    # Sauvegarder
    print("\n💾 Sauvegarde du fichier...")
    save_translations(data)
    
    # Afficher les statistiques
    print("\n📊 Statistiques des traductions:")
    print("=" * 60)
    for lang_code, lang_name in LANGUAGES.items():
        if lang_code in data:
            count = len(data[lang_code])
            print(f"   {lang_name:15} ({lang_code}): {count:4} clés")
    
    print("\n✅ Traductions mises à jour avec succès!")
    print(f"📝 {len(TRANSLATIONS)} nouvelles traductions ajoutées")
    print(f"🌐 {len(LANGUAGES)} langues supportées")
    
    print("\n⚠️  NOTE: Les nouvelles traductions non présentes dans TRANSLATIONS")
    print("   utilisent l'anglais comme fallback. Vous pouvez les modifier")
    print("   manuellement dans traduction.json si nécessaire.")

if __name__ == "__main__":
    main()
