#!/bin/bash
# Configuration Stripe en Production

echo "========================================="
echo "💳 CONFIGURATION STRIPE PRODUCTION"
echo "========================================="
echo ""

echo "📋 Étapes à suivre :"
echo ""
echo "1. 🌐 Aller sur https://dashboard.stripe.com"
echo "   - Se connecter avec votre compte Stripe"
echo "   - Activer le mode LIVE (toggle en haut à droite)"
echo ""

echo "2. 🔑 Récupérer les clés API Live :"
echo "   - Developers > API keys"
echo "   - Copier 'Secret key' (sk_live_...)"
echo "   - Copier 'Publishable key' (pk_live_...)"
echo ""

echo "3. 💰 Créer les produits et prix :"
echo "   - Products > Add product"
echo ""
echo "   Produit 1: Standard"
echo "   - Name: Office1789 Standard"
echo "   - Price: 5 EUR/month"
echo "   - Billing: Recurring monthly"
echo "   - Copier le Price ID (price_...)"
echo ""
echo "   Produit 2: Professional"
echo "   - Name: Office1789 Professional"
echo "   - Price: 12 EUR/month"
echo "   - Billing: Recurring monthly"
echo "   - Copier le Price ID (price_...)"
echo ""
echo "   Produit 3: Enterprise"
echo "   - Name: Office1789 Enterprise"
echo "   - Price: 49 EUR/month"
echo "   - Billing: Recurring monthly"
echo "   - Copier le Price ID (price_...)"
echo ""

echo "4. 🔔 Configurer le Webhook :"
echo "   - Developers > Webhooks > Add endpoint"
echo "   - URL: https://backend.office1789.com/api/stripe/webhook"
echo "   - Events à écouter:"
echo "     * checkout.session.completed"
echo "     * customer.subscription.updated"
echo "     * customer.subscription.deleted"
echo "     * invoice.payment_succeeded"
echo "     * invoice.payment_failed"
echo "   - Copier le Signing secret (whsec_...)"
echo ""

echo "5. ⚙️  Mettre à jour le fichier .env du backend :"
echo "   ssh debian@46.226.107.201"
echo "   nano /home/debian/office1789/backend/.env"
echo ""
echo "   Ajouter/modifier ces lignes :"
echo "   STRIPE_SECRET_KEY=sk_live_VOTRE_CLE_SECRETE"
echo "   STRIPE_WEBHOOK_SECRET=whsec_VOTRE_WEBHOOK_SECRET"
echo "   STRIPE_PRICE_STANDARD=price_VOTRE_PRICE_ID_STANDARD"
echo "   STRIPE_PRICE_PROFESSIONAL=price_VOTRE_PRICE_ID_PROFESSIONAL"
echo "   STRIPE_PRICE_ENTERPRISE=price_VOTRE_PRICE_ID_ENTERPRISE"
echo ""

echo "6. 🔄 Redémarrer le backend :"
echo "   sudo systemctl restart office1789-backend"
echo "   sudo systemctl status office1789-backend"
echo ""

echo "7. ✅ Tester le paiement :"
echo "   - Aller sur https://office1789.com"
echo "   - Se connecter"
echo "   - Aller dans Account > Change subscription"
echo "   - Sélectionner un plan payant"
echo "   - Utiliser une carte de test Stripe: 4242 4242 4242 4242"
echo ""

echo "========================================="
echo "📝 CONFIGURATION FRONTEND"
echo "========================================="
echo ""
echo "Vérifier que le frontend a la clé publique Stripe :"
echo "   Fichier: webfront2/.env.production"
echo "   VITE_STRIPE_PUBLISHABLE_KEY=pk_live_VOTRE_CLE_PUBLIQUE"
echo ""
echo "Si modifié, rebuild le frontend :"
echo "   cd /home/debian/office1789/docker"
echo "   docker compose stop frontend"
echo "   docker compose rm -f frontend"
echo "   docker compose build --no-cache frontend"
echo "   docker compose up -d frontend"
echo ""

echo "========================================="
echo "🧪 TESTS"
echo "========================================="
echo ""
echo "Test 1: Vérifier que Stripe est initialisé"
echo "   curl -X POST https://backend.office1789.com/api/stripe/checkout \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"username\":\"test\",\"token\":\"test\",\"plan_id\":1}'"
echo ""
echo "Test 2: Vérifier le webhook"
echo "   Dashboard Stripe > Webhooks > Cliquer sur votre endpoint > Send test webhook"
echo ""

echo "✅ Configuration Stripe terminée!"
