import os
import subprocess
import sys
from pathlib import Path
import json

print("==========================================")
print("LOCAL DEPLOY (development)")
print("==========================================")

script_dir = Path(__file__).parent.resolve()
repo_dir = (script_dir / "..").resolve()
docker_dir = repo_dir / "docker"
env_file = docker_dir / ".env"
USE_PREBUILT_IMAGES = os.environ.get("USE_PREBUILT_IMAGES", "0") == "1"
BUILD_LOCAL_IMAGES = os.environ.get("BUILD_LOCAL_IMAGES", "0") == "1"


def update_element_config_local(docker_dir: Path) -> None:
    """
    Ensure docker/DockerfileElement/config.json points Element to the
    local Matrix homeserver (http://localhost:8008) for dev.
    """
    config_path = docker_dir / "DockerfileElement" / "config.json"
    data = {
        "default_server_config": {
            "m.homeserver": {
                "base_url": "http://localhost:8008",
                "server_name": "localhost",
            }
        },
        "brand": "Office1789",
        "disable_custom_urls": True,
        "disable_guests": True,
        "default_theme": "light",
        "features": {"voip": True},
    }
    config_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print(f"[ELEMENT] Updated {config_path} with hs=http://localhost:8008")

# Switch frontend env to local
webfront_dir = repo_dir / "webfront2"
switch_env = webfront_dir / "switch_env.py"
if switch_env.exists():
    print("[ENV] switch_env.py local...")
    subprocess.run([sys.executable, str(switch_env), "local"], check=False)
else:
    print("[WARN] switch_env.py not found in webfront2, skipping env switch.")

# ============================
# Generate docker/.env
# ============================
env_content = """# Local dev .env auto-generated by local_deploy.py - safe to keep locally

# Domain and service URLs (local development)
DOMAIN_BASE=localhost
BACKEND_URL=http://localhost:8080
FRONTEND_URL=http://localhost:5173
MAIL_URL=http://localhost:8081
CHAT_URL=http://localhost:3000
DOCS_URL=http://localhost:8082

# Service runtime URLs used by backend for SSO redirects
ROUNDCUBE_URL=http://localhost:8081
ELEMENT_URL=http://localhost:8083

# DB connection (use postgres service in compose)
DB_HOST=postgres_db
DB_PORT=5432
DB_USER=office1789
DB_PASSWORD=office1789
DB_NAME=office1789

# Roundcube IMAP/SMTP (local)
ROUNDCUBE_IMAP_HOST=mailserver:143
ROUNDCUBE_SMTP_HOST=mailserver:587

# Minimal secrets for local dev (do not use in prod)
POSTGRES_USER=office1789
POSTGRES_PASSWORD=office1789
POSTGRES_DB=office1789
ROUNDCUBE_DB_USER=roundcube_user
ROUNDCUBE_DB_PASSWORD=roundcube
ROUNDCUBE_DB_NAME=roundcube
SYNAPSE_DB_USER=synapse
SYNAPSE_DB_PASSWORD=synapse
SYNAPSE_DB_NAME=synapse
SMTP_HOST=mailserver
SMTP_PORT=25
SMTP_FROM=noreply@office1789.com
SMTP_USERNAME=admin
SMTP_PASSWORD=admin
COTURN_SECRET=devcoturn
ONLYOFFICE_JWT_SECRET=devonlyoffice
MATRIX_ADMIN_TOKEN=devmatrixadmintoken
MAIL_ADMIN_USER=admin
MAIL_ADMIN_PASSWORD=admin
STRIPE_SECRET_KEY=sk_test_change_me
STRIPE_WEBHOOK_SECRET=whsec_change_me
STRIPE_PRICE_STANDARD=price_test_standard
STRIPE_PRICE_PROFESSIONAL=price_test_professional
STRIPE_PRICE_ENTERPRISE=price_test_enterprise

# Prebuilt images (optional)
BACKEND_IMAGE=office1789/backend:latest
FRONTEND_IMAGE=office1789/frontend:latest
"""

docker_dir.mkdir(parents=True, exist_ok=True)
env_file.write_text(env_content, encoding="utf-8")
print(f"Generated {env_file}")

# Update Element config for local dev (Matrix on localhost:8008)
update_element_config_local(docker_dir)

# ============================
# Fix line endings in shell scripts (Windows CRLF -> Unix LF)
# ============================
def fix_line_endings(file_path: Path):
    """Convert CRLF to LF for shell scripts"""
    if file_path.exists():
        content = file_path.read_bytes()
        # Replace CRLF with LF
        content = content.replace(b'\r\n', b'\n')
        file_path.write_bytes(content)
        print(f"[FIX] Converted line endings: {file_path}")

# Fix all shell scripts in DockerfileRC
roundcube_dockerfile_dir = docker_dir / "DockerfileRC"
if roundcube_dockerfile_dir.exists():
    for script_file in roundcube_dockerfile_dir.glob("*.sh"):
        fix_line_endings(script_file)

# ============================
# Generate backend/.env.local
# ============================
backend_dir = repo_dir / "backend"
backend_env_local = backend_dir / ".env.local"
backend_env_content = """# Backend local env auto-generated by local_deploy.py

DB_HOST=postgres_db
DB_PORT=5432
DB_USER=office1789
DB_PASSWORD=office1789
DB_NAME=office1789

FRONTEND_URL=http://localhost:5173
MAIL_SERVER=localhost
MAIL_ADMIN_USER=admin
MAIL_ADMIN_PASSWORD=admin
MATRIX_HOMESERVER=http://localhost:8008
MATRIX_ADMIN_TOKEN=devmatrixadmintoken
STRIPE_SECRET_KEY=sk_test_change_me
STRIPE_WEBHOOK_SECRET=whsec_change_me
STRIPE_PRICE_STANDARD=price_test_standard
STRIPE_PRICE_PROFESSIONAL=price_test_professional
STRIPE_PRICE_ENTERPRISE=price_test_enterprise
"""
backend_env_local.write_text(backend_env_content, encoding="utf-8")
print(f"Generated {backend_env_local} (Matrix local config)")

# ============================
# Generate backend/.env
# ============================
backend_env = repo_dir / "backend/.env"
backend_env.write_text(
    "DB_HOST=postgres_db\nDB_PORT=5432\nDB_USER=office1789\nDB_PASSWORD=office1789\nDB_NAME=office1789\n",
    encoding="utf-8",
)
print(f"Generated {backend_env}")

# ============================
# Generate webfront2/.env.local
# ============================
webfront_env_local = webfront_dir / ".env.local"
webfront_env_content = """# URLs de développement (localhost)
VITE_APP_API=http://localhost:8080
VITE_APP_API_LOGIN=http://localhost:8080/api/connect
VITE_APP_API_CREATE_ACCOUNT=http://localhost:8080/api/subscribe
VITE_APP_API_GETINFOP=http://localhost:8080/api/getinfop
VITE_APP_API_CHANGEINFO=http://localhost:8080/api/changeinfo

# Account routes
VITE_APP_API_DELETE_ACCOUNT=http://localhost:8080/api/account/delete
VITE_APP_API_CHANGE_PASSWORD=http://localhost:8080/api/account/change-password

# Password reset
VITE_APP_API_PASSWORD_RESET_REQUEST=http://localhost:8080/api/password/reset/request
VITE_APP_API_PASSWORD_RESET_CONFIRM=http://localhost:8080/api/password/reset/confirm

# Verification
VITE_APP_API_VERIFICATION_SEND=http://localhost:8080/api/verification/send
VITE_APP_API_VERIFICATION_VERIFY=http://localhost:8080/api/verification/verify

# Services URLs (avec ports explicites)
VITE_MATRIX_URL=http://localhost:8008
VITE_ROUNDCUBE_URL=http://localhost:8081
VITE_CHAT_URL=http://localhost:3000
VITE_DOCS_URL=http://localhost:8082
VITE_ELEMENT_URL=http://localhost:8083
VITE_ONLYOFFICE_URL=http://localhost:8082
VITE_FRONTEND_URL=http://localhost:5173

VITE_ENV=development
"""
webfront_env_local.write_text(webfront_env_content, encoding="utf-8")
print(f"Generated {webfront_env_local} (frontend local env)")

print("Bringing up docker compose in development mode")
os.chdir(docker_dir)


def docker_running() -> bool:
    try:
        subprocess.run(["docker", "info"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
        return True
    except Exception:
        return False


if not docker_running():
    print("[WARN] Docker not reachable. Start Docker then run 'docker compose up -d --build'.")
else:
    compose_base = ["docker", "compose", "-f", "docker-compose.yml"]
    if USE_PREBUILT_IMAGES:
        subprocess.run(compose_base + ["pull", "backend", "frontend"], check=False)
        subprocess.run(compose_base + ["up", "-d"], check=False)
    else:
        # Default: build locally using compose build definitions
        subprocess.run(compose_base + ["up", "-d", "--build"], check=False)

    # Align Synapse DB password with docker/.env (dev convenience)
    fix_synapse_script = repo_dir / "scripts/fix_synapse_password.py"
    if fix_synapse_script.exists():
        print("[SYNAPSE] Aligning DB password with docker/.env (local)...")
        subprocess.run([sys.executable, str(fix_synapse_script)], check=False)

    # Setup mail account (wait for mailserver to be ready)
    print("[MAILSERVER] Setting up mail accounts...")
    import time
    time.sleep(5)  # Wait for mailserver to be ready
    
    # Create mail account for matthis@office1789.com
    subprocess.run([
        "docker", "exec", "-it", "mailserver",
        "setup", "email", "add", "matthis@office1789.com", "LCwq?YY=6X%#17"
    ], check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    print("[MAILSERVER] Mail account created: matthis@office1789.com")

print("Local deploy complete.")
