# Auto-updated by config.py
use-auth-secret
static-auth-secret=Mx90qhxjoZwpQPVddkWdZw7vwarDbqWzOmBBQlgmqpCHbjuG
realm=office1789.com
fingerprint
no-tls
no-dtls
listening-port=3478
# Narrow relay port range for Docker Desktop
min-port=49160
max-port=49200
user-quota=12
total-quota=1200
log-file=stdout
simple-log
